### ISSUE TITLE
Project is not refreshed in partial parsing

### ISSUE THREAD

**Issue by max-sixty** [dbt-labs/dbt-bigquery#101]
Thanks as ever for such a brilliant app!

### Describe the bug

Changing the GCP project (e.g. with `gcloud config set project {project}`) and running a dbt command (e.g. `dbt run`) will not update the project with partial parsing. Instead, it's necessary to run `dbt clean` as specified in [parsing known limitations](https://docs.getdbt.com/reference/parsing#known-limitations).

### Steps To Reproduce

```
dbt clean
gcloud config set project project_foo
dbt compile
rg `project_foo` | wc -l  # returns a big number

gcloud config set project project_bar
dbt compile
rg `project_foo` | wc -l  # returns a big number, should return zero
rg `project_bar` | wc -l  # returns zero, should return a big number
```

### Expected behavior

I can understand why dbt doesn't track the implicit GCP project in its cache invalidation logic, and so this is a hard problem to solve.

But I'm not sure it's a necessary problem to _have_. Why does dbt materialize the project name in the queries? If it didn't materialize the projects (arguably by respecting that abstraction), BQ would resolve the implicit project without it being specified, and this would work.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
1.0.1
```

**The operating system you're using:**
MacOS

**The output of `python --version`:**
3.9.9

**Comment by McKnight-42** [comment]
@max-sixty like you say this is a nuisance issue due to state we don't track currently. we have documented shortcomings and a few work arounds for partial parsing including passing the `--no-partial-parse` flag after changing your `gcloud` project.

There is also options of modifying `source` and `ref` macros from default bigquery implementation to not require including the `project` name when it is for a  relation to the same project as connection/default project. 

We'd welcome a contribution for this implementation.
If you'd be interested in contributing to this feature please let us know and we will assist in anyway we can.

**Comment by max-sixty** [comment]
still present

**Comment by max-sixty** [comment]
still present

**Comment by lostmygithubaccount** [comment]
throwing the triage label on for discussion -- is this something we should pick up?

**Comment by Fleid** [comment]
Looking at @McKnight-42's answer (repeated below), I don't think we will prioritize fixing this on our end.

> @max-sixty like you say this is a nuisance issue due to state we don't track currently. we have documented shortcomings and a few work arounds for partial parsing including passing the `--no-partial-parse` flag after changing your `gcloud` project.
> 
> There is also options of modifying `source` and `ref` macros from default bigquery implementation to not require including the `project` name when it is for a relation to the same project as connection/default project.
> 
> We'd welcome a contribution for this implementation. If you'd be interested in contributing to this feature please let us know and we will assist in anyway we can.

I will make it an [`help-wanted`](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) issue for now.
