### ISSUE TITLE
Add macro/run-operation for uploading files from local filesystem to BigQuery.

### ISSUE THREAD

**Issue by NiallRees** [dbt-labs/dbt-bigquery#102]
### Describe the feature
Prompted by https://github.com/brooklyn-data/dbt_artifacts/issues/6.

Access to a macro such as:

{% do adapter.upload_file(file_path, destination) %}
would enable dbt_artifacts to become compatible with BigQuery. It looks as though the function to wrap is [load_table_from_file](https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.load_table_from_file).

### Additional context
Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by McKnight-42** [comment]
@NiallRees Been trying to gather some context on this, seems you have a good idea what path we will need to follow on this, I"m here to assist in anyway I can if you want to work on this.

**Comment by NiallRees** [comment]
Hey @McKnight-42 - I'm going to struggle to get time to contribute this myself, but would love to see this developed!
