### ISSUE TITLE
BigQuery Label Accumulation

### ISSUE THREAD

**Issue by Fraser-Isbester** [dbt-labs/dbt-bigquery#105]
### Describe the feature
BigQuery labels do not accumulate hierarchically unlike most other configurations in dbt.

### Describe alternatives you've considered
You could simply duplicate every collection of labels/tags into the most-nested part of the dbt_project (or within the model config). But that's not really clean/sustainable.

### Additional context
None really.

### Who will this benefit?
Any org that uses BigQuery and not everyone interfaces directly with DBT.

### Are you interested in contributing this feature?
Sure! I am a python developer but don't specifically know how the graph building/hierarchy works but if this is deemed a good first ticket I will gladly take it on.

**Comment by McKnight-42** [comment]
@Fraser-Isbester Thank you for bringing up this issue, seems to be a issue with the default MergeBehavior of the `dbt-bigquery` [ BigqueryConfig](https://github.com/dbt-labs/dbt-bigquery/blob/afd49d92012cd317f144179f4982bb596d01cb3d/dbt/adapters/bigquery/impl.py#L112), and`dbt-core` [MergeBehavior](https://github.com/dbt-labs/dbt-core/blob/1df7a029b4be7c5b79e09bfbcd8ade657df6923e/core/dbt/contracts/graph/model_config.py#L73).

This issue raises the questions of :
- Can we define the adapter configs with non MergeBehavior
- Can we provide a way for users to override default MergeBehavior

I will continue to give any direction towards a possible solution as we discuss them @jtcohen6 [custom merge behavior for configs](https://github.com/dbt-labs/dbt-core/issues/4108) has already been putting a bit of thought into this towards syntax behaviors we could or have tried.

**Comment by McKnight-42** [comment]
Also going to open up an issue in `dbt-core` which will continue some wide reaching possible solution discussions.

**Comment by slve** [comment]
Hi, I actually just faced the same issue this week.
I can confirm that labels from different config levels aren't aggregated.
For example if I add labels into an embedded config in a model (.sql),
then dbt will ignore the additional labels in the dataset's labels config in dbt_project.yml.

```
   dbt --version
Core:
  - installed: 1.1.1
  - latest:    1.1.1 - Up to date!

Plugins:
  - bigquery: 1.1.1 - Up to date!
```

**Comment by dwradcliffe** [comment]
This is very frustrating as someone trying to apply labels at various layers across many projects and datasets. The current way of doing this is unsustainable and although there are workarounds it would be much nicer to support this properly out of the box.

Here is my current workaround:

_`macros/labels.sql`_
```sql
{% macro labels(new_labels) %}
  {{ model.config.get('labels').update(new_labels) | default("", true) }}
{% endmacro %}
```

_`models/model.sql`_
```sql
{{
  labels({
    'foo': 'bar'
  })
}}
```
