### ISSUE TITLE
[ADAP-1075] [Bug] Python models are hard to change after a first run. 

### ISSUE THREAD

**Issue by Lana-hl** [dbt-labs/dbt-bigquery#1059]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Once a Python model has its first run, it's hard to change it later. For instance, first run of the python model creates a table , then trying modify the model to have one more field. And it runs with the error of different schema. So you would have to manually drop the table and re-run the model again. It seems as if Cloud does not support automatic addition of new fields unless you manually delete the underlying table.

### Expected Behavior

Expected to be able to easily modify Python models similar to sql models

### Steps To Reproduce

Created a foo.py model with two fields initially (customer_id and status_id). Once have added the new field (payment_id) to the model temp table was automatically created by dbt on the model run, but unfortunately, these changes don't last and we got an error: expected 2 columns, got 3. So the run has failed and a foo.py model did not get updated with the new field as expected.

### Environment

```markdown
- dbt-core: 1.6.0
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @Lana-hl !

On first blush, this sounds vaguely similar to #1047

Could you provide the relevant log output with the exact error message you got?

To allow us to reproduce this issue on our end, could you provide the example code for a `foo.py`? And also any relevant dbt commands to run?

e.g, we're looking for something similar to this:

`models/foo.py`

```python
import ...

def model(dbt, session):

    my_sql_model_df = dbt.ref("my_sql_model")

    final_df = ...  

    return final_df
```

Commands:
```shell
dbt build -s foo
```

Any other steps that would allow us to reproduce what you are seeing.

**Comment by katerina-kogan** [comment]
Hi @dbeatty10 , thank you for the prompt response and attention to the problem.
We tried to run the model again on the new Dataproc cluster : https://cloud.google.com/dataproc-serverless/docs/release-notes. It has been issued on the 18th of December. And now its working fine, we are able to seamlessly add and remove columns from the python model without manual table deletion.
As we have not changed anything else apart from new Dataproc version, we assumed that could be an issue (which hopefully means its not dbt cloud bug and issue will not reappear!)

I have also updated the thread in dbt community as people were experiencing exactly same problem:
https://discourse.getdbt.com/t/how-to-config-to-allow-new-fields-when-running-pyspark-model-in-gcp-dataproc-serverless/9455/2

Hope it will work for them as well!

**Comment by dbeatty10** [comment]
Glad the new Dataproc version is working for you @katerina-kogan !
And thanks adding your experience to that Discourse post.

I'm going to close this as resolved outside of dbt-biquery -- just let us know if this pops up again and we can either open a new issue or re-open this one.

**Comment by querbesd** [comment]
Hello, 

I would like to reopen the ticket as I face the same issue/bug with the only difference that I am running the pyspark job with dataproc serverless. A simple workaround is to delete the destination table in bigquery and rebuild it. 

Here is the error message I get: 

`Traceback (most recent call last):
  File "/var/dataproc/tmp/srvls-batch-fb9213aa-b2ec-40a3-aae2-a792cd2bb6d5/preproc_ltv.py", line 595, in <module>
    .save("data-warehouse-341717.users.preproc_ltv")
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 968, in save
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o236.save.
: com.google.cloud.spark.bigquery.repackaged.com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInCustomProvider]: IllegalArgumentException: BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema
  at BigQueryDataSourceWriterModule.provideDirectDataSourceWriterContext(BigQueryDataSourceWriterModule.java:60)
  while locating BigQueryDirectDataSourceWriterContext`

Let me know if you need more info. 

Thanks upfront for your assistance🙏
