### ISSUE TITLE
[Bug] Incremental model run `CREATE` statement though the table exists

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-bigquery#1120]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I encountered an issue with the incremental model using dbt-bigquery. Upon investigating the executed BigQuery jobs, I observed unexpected behavior. Specifically, a CREATE OR REPLACE TABLE statement was executed with a WHERE clause using is_incremental(), despite the table’s existence. The expected behavior was the execution of a MERGE statement. This issue did not manifest across all incremental models; it was limited to a few.

Our scheduled jobs are managed through dbt on Google Cloud Composer, a fully managed Apache Airflow service. We leverage the `KubernetesPodOperator` to execute dbt commands within containers. Attempts to replicate the issue locally resulted in the expected execution of a MERGE statement, leaving the root cause of the discrepancy unclear.

The problem first appeared on 2024-02-20. To my knowledge, there were no changes or releases in dbt-core and dbt-bigquery around that time that could have contributed to this issue.

The following configurations define our incremental strategy.
```sql
{{ config(
    materialized="incremental",
    incremental_strategy='insert_overwrite',
    on_schema_change="append_new_columns",
    ...
   )
}}

SELECT ...
FROM ...
{% if is_incremental() %}
WHERE ...
{% endif %}
```

### Expected Behavior

The expected behavior is to run a `MERGE` statement, as the table exists.

### Steps To Reproduce

I haven't understand the steps to reproduce. We saw the issue only on scheduled jobs.

### Environment

```markdown
- Python: 3.11.4
- dbt-core: 1.7.8
- dbt-bigquery: 1.7.6
```

**Comment by colin-rogers-dbt** [comment]
How many times have you observed this behavior?

**Comment by colin-rogers-dbt** [comment]
Also, can you share the complete model `config`?

**Comment by ytd-oc** [comment]
hello
we face exactly the same issue, we exactly the same set up. (composer in prod, kubbernetesoperator, dbt-bigquery) 
with this package versions : 
  Running with dbt=1.8.8
Registered adapter: bigquery=1.8.3

here is an example of node:

`{{ config(
    materialized = 'incremental',
    unique_key= 'pk',
    partition_by={
      'field': 'updated_at',
      'data_type': 'timestamp',
      'granularity': 'day'
    },
    labels = {'data_producer_team': 'dataeng', 'data_owner': 'dataeng' }
    )
}}
--noqa: disable=all
SELECT
    pk,
    allow_attachments,

FROM
    {{ ref('dataeng.raw.golden_raw_tickets_history') }} raw

{% if is_incremental() %}
WHERE
    CAST(raw.updated_at AS TIMESTAMP) >= (
            SELECT
                TIMESTAMP_ADD(
                    MAX(CAST(maxt.updated_at AS TIMESTAMP))
                    , INTERVAL -3 HOUR
                )
            FROM
                {{ this }} maxt
        )
{% endif %}`
