### ISSUE TITLE
[Bug] Incremental model with insert_overwrite strategy does not work with derived/calculated field in partition_by config block 

### ISSUE THREAD

**Issue by chengli-OCADO** [dbt-labs/dbt-bigquery#1129]
### Is this a new bug in dbt-bigquery?

- [x] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running with below config block for incremental model:
```
{{
    config
    (
    materialized = 'incremental',
    unique_key = 'columnA',
    partition_by = { 'field': 'DATE(a_timestamp_column)', 'data_type': 'date' },
    incremental_strategy = 'insert_overwrite',
    cluster_by = ['columnA','columnB','columnC'],
    on_schema_change='append_new_columns',
    )
}}
```

Above configuration in the partition_by resulted in below compiled code:

```sql
when not matched by source
         and date(DBT_INTERNAL_DEST.date(a_timestamp_column)) in unnest(dbt_partitions_for_replacement) 
        then delete
```

Which returned below error:
**Query error: Function not found: DBT_INTERNAL_DEST.date at [29:19]**

### Expected Behavior

Seems the code should be compiled as below in order to be executable:
```sql
when not matched by source
         and date(date(DBT_INTERNAL_DEST.a_timestamp_column)) in unnest(dbt_partitions_for_replacement) 
        then delete
```

### Steps To Reproduce

Use a config like below to define an incremental model would produce the error, please note the partition_by is a date function on a timestamp column.
```
{{
    config
    (
    materialized = 'incremental',
    unique_key = 'columnA',
    partition_by = { 'field': 'DATE(a_timestamp_column)', 'data_type': 'date' },
    incremental_strategy = 'insert_overwrite',
    cluster_by = ['columnA','columnB','columnC'],
    on_schema_change='append_new_columns',
    )
}}
```

### Environment

```markdown
- OS: Sonoma 14.3.1
- Python: 3.12.1
- dbt-core: 1.6.6
- dbt-bigquery: 1.6.7
```

**Comment by github-christophe-oudar** [comment]
If you're going to get `date(date(DBT_INTERNAL_DEST.a_timestamp_column))` why do you need to wrap the it in the configuration and not just set `'field': 'a_timestamp_column'`? What's the use case? Am I missing something?

**Comment by chengli-OCADO** [comment]
Hi Christophe, 
Thanks for replying. I was able to bypass the issue using below with granularity. 
partition_by = { 'field': 'a_time_stamp_field', 'data_type': 'timestamp' , 'granularity': 'day' },
