### ISSUE TITLE
[Bug] Custom Incremental Strategy does not work with BigQuery adapter

### ISSUE THREAD

**Issue by matthieuvilatte** [dbt-labs/dbt-bigquery#1133]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to use Custom Incremental Strategies, dbt raises an error.

### Expected Behavior

The macro which deals with incremental materialization should try to load `get_incremental_STRATEGY_sql ` macros before telling that the strategy is invalid.

### Steps To Reproduce

I followed the documentation for Custom strategies : https://docs.getdbt.com/docs/build/incremental-models#custom-strategies

Create the following macro : 
```
{% macro get_incremental_insert_only_sql(arg_dict) %}

  {% do return(some_custom_macro_with_sql(arg_dict["target_relation"], arg_dict["temp_relation"], arg_dict["unique_key"], arg_dict["dest_columns"], arg_dict["incremental_predicates"])) %}

{% endmacro %}


{% macro some_custom_macro_with_sql(target_relation, temp_relation, unique_key, dest_columns, incremental_predicates) %}

    {%- set dest_cols_csv = get_quoted_csv(dest_columns | map(attribute="name")) -%}

    insert into {{ target_relation }} ({{ dest_cols_csv }})
    (
        select {{ dest_cols_csv }}
        from {{ temp_relation }}
    )

{% endmacro %}
```

And the follwing model : 
```
{{ config(
    materialized="incremental",
    incremental_strategy="insert_only",
) }}

SELECT 1 AS foo
```

### Relevant log output

```shell
Compilation Error in model my_model (models/my_model.sql)
Invalid incremental strategy provided: insert_only
Expected one of: 'merge', 'insert_overwrite'

> in macro dbt_bigquery_validate_get_incremental_strategy (macros/materializations/incremental.sql)
> called by macro materialization_incremental_bigquery (macros/materializations/incremental.sql)
> called by model my_model (models/my_model.sql)
```

### Environment

```markdown
- OS: Docker python:3.8-slim-bullseye
- Python: 3.8
- dbt-core: 1.7.9
- dbt-bigquery: 1.7.6
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @matthieuvilatte !

This hasn't yet been implemented yet, and https://github.com/dbt-labs/dbt-core/issues/9290 covers the remaining work to be done.

Since we already have an issue open for this, I'm going to close this one as a duplicate.
