### ISSUE TITLE
[Bug] Seeds get duplicated in bigquery when service account doesn't have enough permissions

### ISSUE THREAD

**Issue by rodrigo-fss** [dbt-labs/dbt-bigquery#1135]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I run dbt seed, depending on which permissions the service account has, it duplicates the seed's records in bigquery. I imagine it doesn't have enough permissions to truncate the table, but instead of failing on that missing permission, the job skips the deletion part, inserts the data, generates duplicates, and succeeds

### Expected Behavior

Fail the job

### Steps To Reproduce

Create a service account/ assign this set of permissions to your account (make sure those are the only bigquery-related)

```
bigquery.datasets.create
bigquery.jobs.create
bigquery.tables.create
bigquery.tables.delete
bigquery.tables.get
bigquery.tables.getData
bigquery.tables.update
bigquery.tables.updateData
```

and run dbt seeds multiple times

you'll see duplicated records

---

then, to verify it's a permission issue, assign yourself the BigQuery Data Editor role, rerun the seed command and see the duplicates going away (it will truncate the table before inserting the seed data)

### Environment

```markdown
- OS:linux
- Python: 3.9.18
- dbt-core: ">=1.5.0,<1.6.0"
- dbt-bigquery: "1.5.7"
```

**Comment by dataders** [comment]
@rodrigo-fss thanks for opening! I bet this was very tricky to figure out what was going on!


Does this sound like an accurate re-statement of the problem?
> Seed models will have duplicate rows if:
> 1. `dbt seed` is run a second time without `--full-refresh`, and
> 2. User is missing a particular permission (or have duplicative permission)


Your hunch is that the `TRUNCATE` statement fails is a good one, but I cannot find info on [BQ Permissions](https://cloud.google.com/bigquery/docs/access-control#bigquery) related to truncate. It'd be great if we knew for sure what was breaking and why.

One thing you might be able to do is look at the `logs/dbt.log` file too see the exact statements that are run and potentially fail. However dbt-bigquery relies heavily on API calls via the BQ Python SDK, so we might not be able to see the issue there.

However, if we knew exactly the permission set that causes the issue, I'm not sure what could be done within dbt-bigquery to prevent this issue. Perhaps a `dbt debug` check to make sure the user has the right permissions? Regardless this is something we should clearly document to make sure no one else experiences the same issue
