### ISSUE TITLE
[Feature] Log BigQuery console link at the info level (instead of debug level)

### ISSUE THREAD

**Issue by wircho** [dbt-labs/dbt-bigquery#1136]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Change the log level of [the BigQuery console job link](https://github.com/dbt-labs/dbt-bigquery/blob/6c0afe4cfb69761dada5d16150fe632b8f72bf39/dbt/adapters/bigquery/connections.py#L737) from `debug` to `info`

### Describe alternatives you've considered

N/A

### Who will this benefit?

Any team that runs jobs on the cloud (e.g. Airflow).

Debug-level logs, especially with full parse, are extremely verbose and long for large projects. We set our log level to `info` everywhere. So it would be useful to benefit from what is basically _the_ most relevant and actionable information about the job, at the info level.

### Are you interested in contributing this feature?

Yes

**Comment by dschneiderch** [comment]
Definitely still interested! The debug mode is pretty noisy if all you want
is the job link . And it saves me from digging through all the jobs in the
project (we use a DBT runner service account rather than my personal
account) . Maybe there is an in-between option?
