### ISSUE TITLE
[Bug] `pyarrow` not found, install `pyarrow>=3.0.0`

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-bigquery#1152]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

CI failure: https://github.com/dbt-labs/dbt-bigquery/actions/runs/8459554085/job/23176082535

### Expected Behavior

No CI failure

### Steps To Reproduce

https://github.com/dbt-labs/dbt-bigquery/actions/runs/8459554085/job/23176082535

### Relevant log output

```shell
try:
            import pyarrow
        except ImportError as exc:  # pragma: NO COVER
            if raise_if_error:
>               raise exceptions.LegacyPyarrowError(
                    "pyarrow package not found. Install pyarrow version >="
                    f" ***_MIN_PYARROW_VERSION***."
                ) from exc
E               google.cloud.bigquery.exceptions.LegacyPyarrowError: pyarrow package not found. Install pyarrow version >= 3.0.0.
```

### Environment

```markdown
- OS: all
- Python: all
- dbt-core: 1.8
- dbt-bigquery: 1.8
```

**Comment by colin-rogers-dbt** [comment]
issue in bigquery python: https://github.com/googleapis/python-bigquery/issues/1877

**Comment by nvjrepo** [comment]
I have the same issue, someone from DBT team please let me know when this will be resolved
<img width="896" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/103881752/04524c74-1618-4f72-899f-85cf0fa0ba42">

**Comment by davidwitk** [comment]
Hey 👋 Thanks for fixing this quickly! 

Any idea when 1.7.7 will be available on PyPi? Looks like the workflow was cancelled? https://github.com/dbt-labs/dbt-bigquery/actions/runs/8461950493
<img width="1051" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/43667775/472ac5fd-0d66-4a34-81ae-446fffc6dd0a">

**Comment by mikealfare** [comment]
`google-cloud-bigquery` has yanked the offending version (`3.20.0`) from PyPI. The root cause was an undeclared dependency on `pyarrow>=3.0.0`. Folks should be alright to resume their workflows after reinstalling.
