### ISSUE TITLE
Docker image for 1.7.7 became much bigger that 1.7.6

### ISSUE THREAD

**Issue by xemuliam** [dbt-labs/dbt-bigquery#1160]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Looks like smth. goes wrong with version 1.7.7
Changelog is tiny enough but actual size of docker image became unexpectedly big
![image](https://github.com/dbt-labs/dbt-bigquery/assets/20856221/4dc63e33-ad6d-4e1e-8ea9-3ae0480821d1)

### Expected Behavior

I do expect to not see so much growth for image size. There must be very cardinal and significant changes inside to become 42% bigger than previous version

### Steps To Reproduce

pull the 1.7.2, 1.7.4, 1.7.6 and1.7.7 versions from registry and compare sizes

**Comment by dataders** [comment]
@xemuliam https://github.com/dbt-labs/dbt-bigquery/pull/1154's addition of the `[pandas]` option might make the difference? You're right that I don't see much else going on.

I'll flag this internally though, but I'm not sure this qualifies as "bug".

**Comment by xemuliam** [comment]
I understand this issue doesn't look like a bug. However there were very few options to choose issue type

**Comment by mikealfare** [comment]
> @xemuliam #1154 addition of the `[pandas]` option might make the difference? You're right that I don't see much else going on.
> 
> I'll flag this internally though, but I'm not sure this qualifies as "bug".

Agreed, it's very likely `[pandas]`. And now that `google-cloud-bigquery` yanked `3.20`, we can look to see if we can remove that requirement again for the next patch.

And agreed it's not quite a bug, but it's certainly an unexpected change.

**Comment by xemuliam** [comment]
Here is the related information:
https://github.com/googleapis/python-bigquery/pull/1880

**Comment by amychen1776** [comment]
Since dbt 1.7 is at its end of life, I'm going to close out this issue as not going to be do.
