### ISSUE TITLE
[CT-205] Pin version of dbt-core to avoid unexpected broken

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-bigquery#117]
### Describe the feature
At the time of writing the issue, it installs the default branch of dbt-core. But, it potentially causes unexpected broken. For example, the test in https://github.com/dbt-labs/dbt-bigquery/blob/main/tests/integration/docs_generate_tests/test_docs_generate.py#L718 expects the manifest v4. But, what if the manifest v5 is suddenly introduced in the default branch? The test will be broken.

So, it would be good to pin the corresponding version of dbt-core in `dev_requirements.txt`.

```
git+https://github.com/dbt-labs/dbt.git#egg=dbt-core&subdirectory=core
```

**Comment by McKnight-42** [comment]
Thank you for wanting to patch this hole @yu-iskw but we are hesitant to hardcode a version of `dbt-core` as now that we have separated out most of the adapters to their own repos these staggered failures between `core` and `adapter` tests is allowing us to note things like duplication, stress points, which will inevitably allow us to refactor or build better testing foundations and processes. So I will be closing out the issue and PR but please feel free to ask any questions if theres more you'd like to know.
