### ISSUE TITLE
[Bug] Incremental models don't update new elements in struct column

### ISSUE THREAD

**Issue by antoinegenissieux** [dbt-labs/dbt-bigquery#1248]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When a given underlying reference updates a `struct` column by adding new columns to it, changes don't reflect on my incremental table. The process stops mid-way after creating a temp table. A current workaround to this is to either updates schema manually or explicity define all elements in the struct. 

### Expected Behavior

I'm expecting a struct to be fully updated automatically when referencing a table having a struct updated. 

### Steps To Reproduce

1. Create a basic model with a struct in it
2. Create another incremental table based on the first model, it should have the struct field in it.
3. Run both models
4. Append a new sub-column to the first basic model
5. Re-run both models, second doesn't work anymore.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```

**Comment by amychen1776** [comment]
@antoinegenissieux, could you provide the configurations you have for your two incremental models and specifically the [schema change configuration?  ](https://docs.getdbt.com/docs/build/incremental-models#what-if-the-columns-of-my-incremental-model-change)
