### ISSUE TITLE
[Regression] `docs generate` raises error when querying dataset with BQ ML models

### ISSUE THREAD

**Issue by paoloelena15** [dbt-labs/dbt-bigquery#1252]
### Is this a regression in a recent version of dbt-bigquery?

- [X] I believe this is a regression in dbt-bigquery functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

After upgrading to 1.8.1 we are observing the same error that was reported in https://github.com/dbt-labs/dbt-bigquery/issues/1079 and fixed in https://github.com/dbt-labs/dbt-bigquery/pull/1085

Upon comparing the queries run against the dataset in question by dbt-bigquery version 1.7.5 and 1.8.1, we noticed that the coalesce() logic added in #1085 is missing from 1.8.x versions of dbt-bigquery, as well as from the main branch of the repository.

### Expected/Previous Behavior

We expect the docs to be generated successfully, like they were on version 1.7.5. What we see instead is the same issue described in #1079.

### Steps To Reproduce

Run `dbt docs generate` in a project where one of the datasets only contains BQ ML models.

### Environment

```markdown
- OS: Debian 11
- Python: 3.8
- dbt-core (working version): 1.7.8
- dbt-bigquery (working version): 1.7.5
- dbt-core (regression version): 1.8.1
- dbt-bigquery (regression version): 1.8.1
```

**Comment by jtcohen6** [comment]
@paoloelena15 Thanks for raising this! It sounds like the solution here is to forward-port the fix from https://github.com/dbt-labs/dbt-bigquery/issues/1252 into `main` + `1.8.latest`.
