### ISSUE TITLE
[Feature] Retrieving and using table/column descriptions from BigQuery

### ISSUE THREAD

**Issue by K-Oxon** [dbt-labs/dbt-bigquery#1265]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I propose to add functionality to the dbt-bigquery adapter to retrieve and use table and column descriptions directly from BigQuery. This would streamline the process of incorporating existing BigQuery metadata into dbt projects.

Technical approach
One possible implementation would be to modify the _get_dbt_columns_from_bq_table function within the adapter. By extending this function to extract and store the description attribute from BigQuery's SchemaField objects, we could seamlessly integrate these descriptions into the BigQueryColumn representation used by dbt.

https://github.com/dbt-labs/dbt-bigquery/blob/0627aa2ec5283fdc3f7df43865d37e3612f3df5b/dbt/adapters/bigquery/impl.py#L393

### Describe alternatives you've considered

Currently, to get table/column descriptions into dbt, you have to copy them manually or write custom scripts. This is time consuming and error prone.

### Who will this benefit?

This feature would be invaluable for

Data engineers and analysts: They could quickly bootstrap DBT projects using existing BigQuery metadata, saving significant time and effort.
Teams with established BigQuery metadata: This would enable a smooth transition to dbt, leveraging their existing documentation and knowledge.
Users of dbt-codegen and dbt-osmosis: These tools could automatically incorporate descriptions into generated dbt models.

**Comment by amychen1776** [comment]
This is a great idea. However, given our north star around adapters/dbt core being stateless, this is not a feature functionality we will support in dbt-bigquery but rather an interface like dbt Cloud that can better manage metadata.
