### ISSUE TITLE
[CT-349] Add test for load_dataframe

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-bigquery#134]
While working on https://github.com/dbt-labs/dbt-bigquery/pull/121 the contributor noticed that similar funcitonality of `load_dataframe` did not contain any integration testing these should be built and a good framework could be from the mentioned PR.

### Additional context
Should have capability to test that dataframes are loaded and can pull down information

### Who will this benefit?
all who use load_dataframe to add files to their project to insure stability of funcitonality.

**Comment by jtcohen6** [comment]
The `load_dataframe` method is used for seeds on BigQuery:
https://github.com/dbt-labs/dbt-bigquery/blob/a426d3aaee7cb2b642fc0cbfe421d785c67529e3/dbt/include/bigquery/macros/materializations/seed.sql#L13-L14

Still, I'm sure we can always use more tests :)
