### ISSUE TITLE
[Bug] New RANGE type in bigquery failing when setting descriptions

### ISSUE THREAD

**Issue by borjavb** [dbt-labs/dbt-bigquery#1341]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using the new [RANGE type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#range_type), in a model, the model will be created correctly, but dbt will fail while trying to update the descriptions of the schema:
``` 400 PATCH <> Range field <field> must have a range element type.```

The new SchemaField for RANGE data types expects an extra parameter `range_element_type` with values {date,datetime,timestamp} in order to work https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.schema.SchemaField

### Expected Behavior

dbt runs correctly and applies the column descriptions without erroring

### Steps To Reproduce

Create a model with its respective yaml file description, and run it

table_a.sql
```sql
SELECT RANGE(DATE '2021-01-01', DATE '2023-01-01') column_range
```
table_a.yaml
```yaml
models:
  - name: table_a
    description: something
    columns:
      - name: column_range
        description: placeholder
```

### Relevant log output

```shell
400 PATCH <> Range field column_range must have a range element type.
```

### Environment

```markdown
- OS: Mac Os m1
- Python: 3.9
- dbt-core: 1.8
- dbt-bigquery: v1.8.2
```

**Comment by anaghshineh** [comment]
Hey, @borjavb. I was interested in this and took a quick look. Seems to work for me based on some cursory playing around. **Are you able to confirm what version of `google-cloud-bigquery` is running under the hood?**

A few observations:

- Looks like the `SchemaField` class now requires `range_element_type` for fields with type `RANGE` in later versions (as you mentioned)
- Support for `range_element_type` was [added in version `3.15.0`](https://cloud.google.com/python/docs/reference/bigquery/3.15.0/google.cloud.bigquery.schema.SchemaField), but it's not present in the [prior `3.14.1` version](https://cloud.google.com/python/docs/reference/bigquery/3.14.1/google.cloud.bigquery.schema.SchemaField)
- I tested this adapter's logic [here](https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/adapters/bigquery/impl.py#L631-L646) with a pre-existing table containing a field of type `RANGE` to try to update the description
  - When I explicitly had `google-cloud-bigquery==3.15.0`, it worked just fine
  - When I explicitly downgraded to `google-cloud-bigquery==3.14.1`, I hit the same error you mentioned in this issue
