### ISSUE TITLE
[Feature] Support `google.auth.credentials.AnonymousCredentials` for bigquery enabling to unit test models.

### ISSUE THREAD

**Issue by shrivastava-ankur** [dbt-labs/dbt-bigquery#1377]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Support `google.auth.credentials.AnonymousCredentials` for bigquery enabling to unit test models in isolation locally.
- use of `AnonymousCredentials`
- Ability to pass `api_endpoint` as `client_options` to client instantiation 

### Describe alternatives you've considered

No available options to connect to [bigquery-emulator](https://github.com/goccy/bigquery-emulator) instance for isolated testing.

### Who will this benefit?

All the dbt developers using `bigquery` will be benefitted, as this change would allow them to test the models in isolation.

### Are you interested in contributing this feature?

Yes, I am ready with the changes.

**Comment by amychen1776** [comment]
Thank you for opening up this issue! At this time we are not prioritizing supporting the BQ emulator so I am going to close this issue out for now.

**Comment by nightscape** [comment]
Hi @amychen1776, I think this would be quite helpful.
@shrivastava-ankur created a PR for it, which now has conflicts due to refactorings, but could be ported forward (which I'd be happy to do).
It's actually just ~20 added lines of code, so it hopefully doesn't burden future maintenance.

**Comment by jtcohen6** [comment]
@nightscape See the related conversation in a similar PR:
- https://github.com/dbt-labs/dbt-bigquery/pull/1017#issuecomment-2515615143
