### ISSUE TITLE
[CT-361] Bump up to 1.0.3

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-bigquery#139]
### Describe the feature
The default branch is linked to dbt-core 1.0.0.  For instance, dbt exposures on dbt docs don't appear appropriately. To fix the issue,  let's bump up to 1.0.3.
https://github.com/dbt-labs/dbt-core/issues/4520

As far as I know, the version of dbt-bigquery is dynamically linked with that of dbt-core using `__version__.py`.
https://github.com/dbt-labs/dbt-bigquery/blob/main/setup.py#L31-L43

**Comment by jtcohen6** [comment]
@yu-iskw Thanks for opening, and for taking a look at this logic! Starting in v1.0, dbt plugin versions are linked to `dbt-core` minor versions. The installation logic always installs the latest compatible patch for that minor version.

https://github.com/dbt-labs/dbt-bigquery/blob/a426d3aaee7cb2b642fc0cbfe421d785c67529e3/setup.py#L46-L51

https://github.com/dbt-labs/dbt-bigquery/blob/a426d3aaee7cb2b642fc0cbfe421d785c67529e3/setup.py#L70-L71

Currently, this translates to `dbt-core~=1.0.0`, which resolves to `dbt-core==1.0.3`. You may just need to update your local installation to see that take effect:
```
pip install dbt-core dbt-bigquery --upgrade
```

It's understood that the patch number reflects fixes only, and may not match the patch number for `dbt-core` or other plugins. As long as the major + minor numbers match, and you've installed the latest available patch of each one, you're in good shape.

- Docs on this: https://docs.getdbt.com/docs/core-versions#how-we-version-adapter-plugins
- Improvements to `dbt --version` to make this even clearer: https://github.com/dbt-labs/dbt-core/issues/4724
