### ISSUE TITLE
Report bytes processed after running BigQuery SQL

### ISSUE THREAD

**Issue by watermanio** [dbt-labs/dbt-bigquery#14]
### Describe the feature
As BigQuery bills users based on the volume of data processed, it's fairly important for users to be aware of this while developing models and pipelines. In the BQ UI this is fairly clearly presented after each query run, and the same information is available in the [`jobs.query`](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query) API response.

You can find the `totalBytesProcessed` documented in the linked API documentation. 

It would be helpful to see this output in the JSON logging - example:

```json
{"timestamp": "2020-01-30", "message": "13:25:37 | 24 of 27 OK created incremental model dbt_andy.customers............. [CREATE TABLE (450) in 2.82s]", "channel": "dbt", "level": 11, "levelname": "INFO", "extra": {"unique_id": "model.customers", "bytes_processed": 4882}}
```

And also at the end of a run with the default log formatter:

```
13:16:52 | Finished running 23 incremental models, 4 table models, 1 hook in 35.87s
13:16:52 | 750mb of data processed
```

### Describe alternatives you've considered
If you have enabled Export To BigQuery within your Google Cloud billing project, it would be possible to query how much data the service account your DBT user has processed. This could then be queried and monitored outside of DBT, but it would be so much helpful to have an indication of query size in realtime - this is an important optimisation when building BigQuery pipelines. 

### Who will this benefit?
This is very important for all users of BigQuery who have enough data stored to have a reasonable spend, but who are not so large that they have purchased commitments (flat fee / all you can eat) from Google. Even then, it's still best practice to pay attention to how much data you are processing...

**Comment by elyobo** [comment]
Still seems worth doing bot, please reopen.

**Comment by elyobo** [comment]
There's also no logging _at all_ of this data usage from tests, which is a potential cost iceberg (especially with BQ and some of the tests having had `SELECT *` behaviour at times), exposing that information would be fantastic as well. I don't know if that's also hidden in the internals somewhere as @jtcohen6 mentions is the case for the run stuff (I guess it would be if it's being collected in the adapter?).
