### ISSUE TITLE
[Feature] Custom incremental strategies supported on BigQuery

### ISSUE THREAD

**Issue by jackodes** [dbt-labs/dbt-bigquery#1406]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm trying to implement a custom incremental strategy based on [this](https://docs.getdbt.com/docs/build/incremental-strategy#custom-strategies) documentation.

But there's a specific [macro](https://github.com/dbt-labs/dbt-bigquery/blob/1fe273a9de73a950429f00b90a48b95cf91d328f/dbt/include/bigquery/macros/materializations/incremental.sql#L1) on dbt-bigquery that checks for the name of the incremental strategy and raises an error in case it's none of the predefined ones:

``` 
{% macro dbt_bigquery_validate_get_incremental_strategy(config) %}
  {#-- Find and validate the incremental strategy #}
  {%- set strategy = config.get("incremental_strategy") or 'merge' -%}

  {% set invalid_strategy_msg -%}
    Invalid incremental strategy provided: {{ strategy }}
    Expected one of: 'merge', 'insert_overwrite', 'microbatch'
  {%- endset %}
  {% if strategy not in ['merge', 'insert_overwrite', 'microbatch'] %}
    {% do exceptions.raise_compiler_error(invalid_strategy_msg) %}
  {% endif %}

  {% if strategy == 'microbatch' %}
    {% do bq_validate_microbatch_config(config) %}
  {% endif %}

  {% do return(strategy) %}
{% endmacro %}
```

### Expected Behavior

The expected behavior is that it checks for custom incremental strategies as in the doc I shared and set it as valid in case it exists.

### Steps To Reproduce

1. dbt cloud (versionless env)
2. Use an environment connected to a BigQuery project
3. Create a custom incremental strategy macro (mine was named `get_incremental_merge_upsert_sql`) 
4. Create an incremental model based on that, as an example:
``` 
{{ config(
    materialized='incremental',
    incremental_strategy='merge_upsert',
    unique_key='id'
) }}

``` 

5. Build the model

### Relevant log output

```shell
Invalid incremental strategy provided: merge_upsert
      Expected one of: 'merge', 'insert_overwrite', 'microbatch'
  
  > in macro dbt_bigquery_validate_get_incremental_strategy (macros/materializations/incremental.sql)
  > called by macro materialization_incremental_bigquery (macros/materializations/incremental.sql)
  > called by model stg_mymodel (models/stg/stg_mymodel.sql)
```
```


### Environment

```markdown
- dbt cloud versionless
```

**Comment by amychen1776** [comment]
Hello @jackodes! Unfortunately we actually don't support Custom Incremental Stratergies on BQ at this time.  Please see this issue that covers the remaining work https://github.com/dbt-labs/dbt-core/issues/9290

What I'm going to do is actually close this issue for the time (since we are tracking on that dbt-core issue and this is a duplicate) and get our docs updated accordingly to call out this.
