### ISSUE TITLE
[Feature] Microbatch should allow copy_partitions

### ISSUE THREAD

**Issue by jschintz-nytimes** [dbt-labs/dbt-bigquery#1414]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Merging in BQ is great - [but not always the most performant](https://docs.getdbt.com/blog/bigquery-ingestion-time-partitioning-and-partition-copy-with-dbt)

Allow for the existing feature "copy_partitions" to be available in the microbatch incremental strategy

### Describe alternatives you've considered

Write a custom strategy

### Who will this benefit?

Anyone using microbatch

### Are you interested in contributing this feature?

Maybe!

**Comment by borjavb** [comment]
If I'm not mistaken I think `copy_partitions` is already working with `microbatch`.

`microbatch` under the hood relies on `insert_overwrite` and the copy_partitions config is being set through all the new `microbatch` logic.

**Comment by jschintz-nytimes** [comment]
> If I'm not mistaken I think `copy_partitions` is already working with `microbatch`.
> 
> `microbatch` under the hood relies on `insert_overwrite` and the `copy_partitions` config is being set through all the new `microbatch` logic.
> 
> https://github.com/dbt-labs/dbt-bigquery/blob/8c2d9bbca4ac42cd6f05d10cab42036bbd125efa/dbt/include/bigquery/macros/materializations/incremental_strategy/microbatch.sql#L20-L28

@borjavb I think that's just passing a required parameter with the default, false.
I'm seeing merge strategy being used in the microbatch run code.

```
    merge into `nyt-enterprise-reporting-dev`.`dbt_cloud_pr_00000_000`.`microbatch` as DBT_INTERNAL_DEST
        using (
        select
        * from `nyt-enterprise-reporting-dev`.`dbt_cloud_pr_00000_000`.`microbatch`
      ) as DBT_INTERNAL_SOURCE
        on FALSE

    when not matched by source
         and date(DBT_INTERNAL_DEST.partitiontime) in unnest(dbt_partitions_for_replacement) 
        then delete

    when not matched then insert
        (`fields`)
    values
        (`fields`)

;
```

**Comment by borjavb** [comment]
You are right, is not working. Sorry!

I think I found the issue, basically there's a conditional check where `copy_partitions` can only be set on `insert-overwrite`, and it was not updated to accept `microbatch`. Let me open a PR.

 ------
How to reproduce:
```
{{ config(
    materialized='incremental',
    incremental_strategy='microbatch',
    event_time='session_start',
    begin='2024-12-02',
    batch_size='day',
    lookback = 1,
    partition_by={
      'field': 'session_start',
      'granularity': 'day',
      "copy_partitions": true
    }
) }}
select CURRENT_DATE() as session_start
```

That trigger this line
https://github.com/dbt-labs/dbt-bigquery/blob/62695c9322f71339fd0cc839761643244d4d7ad1/dbt/include/bigquery/macros/materializations/incremental.sql#L98-L102

**Comment by borjavb** [comment]
https://github.com/dbt-labs/dbt-bigquery/pull/1421/files This should do it!

But I wonder if we should default `copy_partitions` as true for `microbatch`... It might be the best option for this operation really...

**Comment by MichelleArk** [comment]
Closed by https://github.com/dbt-labs/dbt-bigquery/pull/1421, this will go out in the next 1.9 patch (1.9.1)
