### ISSUE TITLE
[CT-412] Support the latest patch release of dbt-core

### ISSUE THREAD

**Issue by kopackiw** [dbt-labs/dbt-bigquery#144]
### Describe the feature
`dbt-bigquery` is currently pinned to a version of `dbt-core` where major and minor are the same as the plugin, but [the patch part is always `0`](https://github.com/dbt-labs/dbt-bigquery/blob/main/setup.py#L49). It would be nice not to hardcode it and follow the latest release of `dbt-core` within major and minor parts.

### Describe alternatives you've considered
None.

### Additional context
I have a container with both `dbt` v0.21.0 and `flask` v1.1.4. When I want to upgrade to the latest version of dbt (via this plugin), I'm fetching a `dbt-core` v1.0.0, but it's not compatible (see log A) with a flask version. Also, upgrading flask to latest v2 where it supports click>=8 does not help as there is another dependency conflict (see log B). [The PR was merged](https://github.com/dbt-labs/dbt-core/pull/4817/files) into `dbt-core` that relax the version constraint, and it was released under v1.0.3. However, I'm not able to use this, as the plugin always take the oldest patch release.

Log A
```
    flask 1.1.4 depends on click<8.0 and >=5.1
    dbt-core 1.0.0 depends on click<9 and >=8
```

Log B
```
    flask 2.0.3 depends on Jinja2>=3.0
    dbt-core 1.0.0 depends on Jinja2==2.11.3
```

### Who will this benefit?
Anyone who have uses both `flask` and `dbt` in one container and want to upgrade to v1. Also, it may resolve similar cases in next releases.

### Are you interested in contributing this feature?
I may be interested but need some guidance.

**Comment by kopackiw** [comment]
Waiting for `dbt-core` v1.0.5 release. It's still a release candidate. It contains a PR with dependency issue fix. That should solve a problem when released officially 👍🏻

**Comment by jtcohen6** [comment]
@kopackiw For posterity: The patch number is indeed set at `0`, but we use the [compatible release operator](https://peps.python.org/pep-0440/#compatible-release) (`~=`) to ensure that the latest compatible patch is always installed:

https://github.com/dbt-labs/dbt-bigquery/blob/a426d3aaee7cb2b642fc0cbfe421d785c67529e3/setup.py#L71

After running `pip install dbt-bigquery` in a fresh env:
```
$ dbt --version
installed version: 1.0.4
   latest version: 1.0.4

Up to date!

Plugins:
  - bigquery: 1.0.0 - Up to date!
```

If you want to try out `dbt-core==1.0.5rc1` while it's a prerelease, try `pip install --pre dbt-core dbt-bigquery`:
```
$ dbt --version
installed version: 1.0.5-rc1
   latest version: 1.0.4

Your version of dbt is ahead of the latest release!

Plugins:
  - bigquery: 1.0.0 - Up to date!
```

**Comment by kopackiw** [comment]
Oh, I didn't know about this operator! Thank you for detailed explanation 🙇🏻

**Comment by kopackiw** [comment]
I've spotted that there are some issues addressing a similar topic. Maybe it's worth to remove this misleading [`.0` patch part](https://github.com/dbt-labs/dbt-bigquery/blob/main/setup.py#L49) (as the patch version does not matter with this operator) and add a comment in the code that it's always the latest patch version. What do you think, @jtcohen6 ? 🤔

**Comment by jtcohen6** [comment]
@kopackiw Appreciate the thought you've given this! You're right, this has caused confusion for other folks too.

I _believe_:
- `pip install dbt-core~=1.0.0` will install the latest compatible `1.0.x` (what we want)
- `pip install dbt-core~=1.0` will install the latest compatible `1.x` — i.e. it will install v1.1 as soon as it has its final release. I don't think that's what we want.
- `pip install dbt-core==1.0` will always install `1.0.0` exactly

The alternative is a slightly more verbose expression, to achieve the same behavior as the first `~=` operator:
```
'dbt-core>=1.0.0,<1.1.0'
```
That may be worth it, if it yields greater clarity for end users. We could also annotate `setup.py` to make the intention clear.

**Comment by kopackiw** [comment]
Yeah, you're right, I misunderstood the mechanism where there is no patch version provided (checked with `pip install pipdate~=0.4`, got v0.5.5 which is the latest).

I think that a comment (example below) will be enough for future users; no need to rewrite for more verbosity.

> `~=x.y.0` is an equivalent of `>=x.y.*`, so always the latest patch version is fetched.


Thanks for correcting my misunderstanding and populating my "Today I Learned" list 🙇🏻
