### ISSUE TITLE
[CT-451] upload_file macro does not work for run_results.json

### ISSUE THREAD

**Issue by pgoslatara** [dbt-labs/dbt-bigquery#152]
### Describe the bug
The `upload_file` macro does not work with `run_results.json` as the file does not conform to BigQuery's accepted file formats as it can contain empty dict's as values, for example "... "env": {} ...".

### Steps To Reproduce
`dbt -d run-operation upload_file --args "{local_file_path: './target/run_results.json', database: '<GCP_PROJECT>', table_schema: '<DATASET>', table_name: '<TABLE_NAME>', autodetect: True, write_disposition: 'WRITE_TRUNCATE', source_format: 'NEWLINE_DELIMITED_JSON'}"`

### Expected behavior
A single row is added to the specified table.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
installed version: 1.1.0-b1
   latest version: 1.0.4

Your version of dbt is ahead of the latest release!

Plugins:
```

**The operating system you're using:**
Ubuntu 20.04

**The output of `python --version`:**
Python 3.9.10

**Comment by McKnight-42** [comment]
@pgoslatara this is a great catch and follow up to your previous work, excited to help you as needed please let me know.

**Comment by pgoslatara** [comment]
Thanks @McKnight-42. I'm all good with the associated PR, I think it's an elegant solution to this issue, so happy to wait until you've had time to review.
