### ISSUE TITLE
[CT-574] Include table description in catalog

### ISSUE THREAD

**Issue by halvorlu** [dbt-labs/dbt-bigquery#173]
### Describe the feature
The `catalog.json` file should contain the table description fetched from the BigQuery database. This will enable us to show the table description for sources in the docs, without having to specify it in a YAML file. If a source table already exists in the database, it typically has a description which we would like to see in the docs, without having to repeat it in the YAML file. See also https://github.com/dbt-labs/dbt-docs/pull/263, which will fetch the table description from `catalog.json`.

### Describe alternatives you've considered
An alternative could be to manually copy the table description into the sources.yml file, but that would mean a lot of manual work.

### Who will this benefit?
All users that have source tables with documentation that they want to explore in dbt docs.

### Are you interested in contributing this feature?
Yes, working on a PR right now.

**Comment by jtcohen6** [comment]
@halvorlu Thanks for opening the issue, and for the PR! This seems totally reasonable to me
