### ISSUE TITLE
[CT-578] Allow additional partition configurations to be updated

### ISSUE THREAD

**Issue by philippama** [dbt-labs/dbt-bigquery#175]
### Describe the bug
[Additional partition configuration options](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#additional-partition-configs) `require_partition_filter` and `partition_expiration_days` have been supported since v0.20.0 for `table` and `incremental` models. However, these configuration options are only applied when the table is created. This is fine for table models, whose tables are (re-)created each time they are run, but it means that changes to partition options in incremental models are never actioned.

For example, if we set `partition_expiration_days` on incremental models, the table’s partition expiration is set when the table is created. If we change the value or attempt to set partition expiration once the table has already been created, the new partition expiration value is not set. Not only is the new partition expiration value not set, but we now have a configuration block for our model which does not tell the truth about the model state. The same applies to `require_partition_filter`.

### Steps To Reproduce
The model
```
{{
  config(
    materialized = 'incremental',
    incremental_strategy = 'insert_overwrite',
    partition_by = {'field': 'date', 'data_type': 'date'},
    partition_expiration_days = 365,
    require_partition_filter = true
  )
}}

SELECT DATE('2022-01-01') AS date, "Hard-coded date" AS description, CURRENT_TIMESTAMP() AS insert_time
```

generates the run SQL (some blank lines have been removed):

```
  create or replace table `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example`
  partition by date
  
  OPTIONS(
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 72 hour),
    
      description="""""",
    
      require_partition_filter=True,
    
      partition_expiration_days=365
    )
  as (
SELECT DATE('2022-01-01') AS date, "Hard-coded date" AS description, CURRENT_TIMESTAMP() AS insert_time
  );
```

Then when I change the config values:

```
{{
  config(
    materialized = 'incremental',
    incremental_strategy = 'insert_overwrite',
    partition_by = {'field': 'date', 'data_type': 'date'},
    partition_expiration_days = 30,
    require_partition_filter = false
  )
}}

SELECT DATE('2022-01-01') AS date, "Hard-coded date" AS description, CURRENT_TIMESTAMP() AS insert_time
```

the  update SQL has no mention of them (some blank lines have been removed):

<details>
  <summary>Click to expand the long run SQL</summary>
  <p>

```
      -- generated script to merge partitions into `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example`
      declare dbt_partitions_for_replacement array<date>;
        
        -- 1. create a temp table

  create or replace table `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example__dbt_tmp`
  partition by date
  
  OPTIONS(
      description="""""",
    
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 hour)
    )
  as (
    
WITH
hack_to_prevent_failing_orphan_script_check AS (
  SELECT * FROM `at-data-platform-preprod`.`stock_platform__marketplace_stock`.`search_stock_snapshot_daily_view_v1`
)

SELECT DATE('2022-01-01') AS date, "Hard-coded date" AS description, CURRENT_TIMESTAMP() AS insert_time
  );
      
      -- 2. define partitions to update
      set (dbt_partitions_for_replacement) = (
          select as struct
              array_agg(distinct date)
          from `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example__dbt_tmp`
      );

      -- 3. run the merge statement

    merge into `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example` as DBT_INTERNAL_DEST
        using (
        select * from `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example__dbt_tmp`
      ) as DBT_INTERNAL_SOURCE
        on FALSE

    when not matched by source
         and DBT_INTERNAL_DEST.date in unnest(dbt_partitions_for_replacement) 
        then delete

    when not matched then insert
        (`date`, `description`, `insert_time`)
    values
        (`date`, `description`, `insert_time`)
;

      -- 4. clean up the temp table
      drop table if exists `at-data-platform-preprod`.`pm_spike`.`for_dbt_issue_example__dbt_tmp`
```

  </p>
</details>

### Expected behavior

Updates to the additional partition configuration options should be actioned.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
installed version: 1.0.4
   latest version: 1.0.6

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.0.0 - Up to date!
```

**The operating system you're using:**

**The output of `python --version`:**
```
Python 3.8.12
```

### Additional context
We are currently working around the problem by using this post-hook:
```
{% macro update_bigquery_table_partition_options(table_ref) -%}
{#-
This updates partition options. dbt only sets partition options when the table is created. This is fine for table
models, whose tables are (re-)created each time they are run, but it means that changes to partition options in
incremental models are never actioned.

Running this as a post-hook ensures that partition option changes are actioned for all incremental models.
-#}
{%- if config.get('materialized') == 'incremental' and config.get('partition_by') is not none -%}
    ALTER TABLE {{ table_ref }}
    SET OPTIONS (
        {%- if config.get('partition_by').get('data_type') in ['timestamp', 'date', 'datetime'] -%}
        partition_expiration_days={{ config.get('partition_expiration_days') if config.get('partition_expiration_days') is not none else 'NULL' }},
        {%- endif %}
        require_partition_filter={{ config.get('require_partition_filter') if config.get('require_partition_filter') is not none else 'false' }}
    );
{%- endif %}
{%- endmacro %}
```

**Comment by McKnight-42** [comment]
@philippama Thank you for opening up this issue!! and this sounds like a completely reasonable ask. going to change up the tags a little for this one this seems more feature or possible extension of existing feature.

there are two quick thoughts on this.
- a simpler and good first issue solution might be to to update the config during incremental runs a good example would be something like [bigquery table options](https://github.com/dbt-labs/dbt-bigquery/blob/8aaa6ab6da182aa8e831f631feb12af5ec76d9ce/dbt/include/bigquery/macros/adapters.sql#L39-L42).
- A more complete complex solution would check the current table see what configs have changed and apply those.

please let me know if you'd like to like to give implementing this a try i'd be more than happy to help you along the way!
