### ISSUE TITLE
[CT-593] `--store-failures` flag causes DATABASE ERROR because of unnamed column in DDL 

### ISSUE THREAD

**Issue by vlad-ds** [dbt-labs/dbt-bigquery#178]
### Describe the bug
An otherwise functioning dbt test produces DATABASE ERROR on BigQuery when running with the `--store-failures` flag. The backend code that stores failures in the `dbt_test__audit` database fails because it has a column with no alias. See code below. 

### Steps To Reproduce
Running a test on a BigQuery table with the `--store-failures` flag. Not clear on how to reproduce because it only happens on particular tables and I'm not sure why. 

### Expected behavior
The test should run successfully even with the `--store-failures-flag`. 

### Screenshots and log output
This is the error:
```
Database Error in test <test-name>
CREATE TABLE columns must be named, but column 1 has no name at [9:6]
```

This is the code that dbt runs in the backend: 

```
  CREATE OR REPLACE TABLE `project`.`dbt_test__audit`.`validate_data_actuality_fact_f_022bfd35658a4e405e26910fe10839d5`
  OPTIONS()
  AS (

SELECT  1=1,
  MAX(ref_date) AS last_update,
  TIMESTAMP_DIFF(CURRENT_DATE, MAX(ref_date), DAY) AS datepart_since_update,
  1 -  DATE_DIFF(CURRENT_DATE, MAX(ref_date), DAY) AS diff
FROM
  `project`.`dataset`.`table`
  GROUP BY  1=1 
   HAVING (1 -  DATE_DIFF(CURRENT_DATE, MAX(ref_date), DAY)) < 0
  );
```

The problem is in the `SELECT 1=1` part which AFAIK is added by dbt. The absence of an alias causes a database error. Correcting this to `SELECT 1=1 AS col` solves the error. 

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.0 - Up to date!

Plugins:
  - bigquery:  1.1.0  - Up to date!
```

**The operating system you're using:**
macOS Big Sur 11.6.1

**The output of `python --version`:**
Python 3.7.10

### Additional context
We are planning to use the `--store-failures` flag on all our tests to facilitate reading test failures. In this case we are using a custom test. But the `SELECT 1=1` part which is causing the database error is not in our test macro.

**Comment by jtcohen6** [comment]
@vlad-ds Thanks for opening!

> The problem is in the SELECT 1=1 part which AFAIK is added by dbt.

I don't think this is right. This is coming from the test definition, which seems to be a [custom generic test](https://docs.getdbt.com/docs/guides/writing-custom-generic-tests) defined outside of `dbt-core`.

Given the name of your test, I'd guess the name of that custom generic test is something like `validate_data_actuality`. Could you look to see where it might be defined? Possibly in the `macros/` folder of your project, or in an installed package?

**Comment by vlad-ds** [comment]
Hi jtcohen, like you said it was a problem with a custom test. Thank you.
