### ISSUE TITLE
[CT-614] incremental model fails to remove __dbt_tmp table

### ISSUE THREAD

**Issue by cwelton** [dbt-labs/dbt-bigquery#184]
### Describe the bug

DBT is creating __dbt_tmp tables and never cleaning them up.

### Steps To Reproduce

Seems to involve an incremental model with MERGE strategy and `on_schema_change='fail'`

E.g. this code path: https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/include/bigquery/macros/materializations/incremental.sql#L177

### Expected behavior
temp tables should always be cleaned up after they have been used.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.0
  - latest:    1.1.0 - Up to date!

Plugins:
  - bigquery: 1.1.0 - Up to date!
```

**The operating system you're using:**
OSX, ubuntu

**The output of `python --version`:**
3.9.10

**Comment by cwelton** [comment]
Probably related to https://github.com/dbt-labs/dbt-bigquery/issues/154, but here the cause is the `on_schema_change` spec not a failed build.

**Comment by resigo** [comment]
I am experiencing the same issue, incremental model works (renames correctly real temporary tables) when `on_schema_change` is not defined. However, once we define `on_schema_change` to any value in `dbt_project.yml`, the tables with `__dbt_temp` do not get renamed and "hang" in dataset.

**Comment by cwelton** [comment]
@McKnight-42 What I was trying to accomplish was "if the schema changes just do a full rebuild not an incremental build".  Which is, I believe, a different use case than #154 or #163.   To accomplish this I initially set `on_schema_change=sync_all_columns`, that didn't give me what I wanted, so I just switched to `on_schema_change=fail` as outlined here: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models#what-if-the-columns-of-my-incremental-model-change

Which would at least let me know that I needed to do a --full-refresh rather than doing an incremental rebuild that may not do the right thing with the schema change.

**Comment by rpedela-recurly** [comment]
I have an incremental model that I want to run hourly with `on_schema_change=sync_all_columns`. Do the temp tables need to persist for a particular amount of time for `on_schema_change` to function? Is there any harm in manually cleaning them up a `post_hook`?

**Comment by Fleid** [comment]
@cwelton I reproduced the behavior on `1.4.0`, but I don't think there's an issue with it.

The temporary tables that are created on BigQuery are actually not temporary objects. Looking at that [comment](https://github.com/dbt-labs/dbt-bigquery/issues/163#issuecomment-1110815079) from @jtcohen6:

> For context, [BigQuery only supports _real_ temporary tables within the context of a multi-statement query](https://cloud.google.com/bigquery/docs/multi-statement-queries#temporary_tables) ("scripting"). This makes sense, since BQ otherwise doesn't have a notion of sessions or transactions. The temp table naturally expires at the end of the script.
> 
> Given that limitation, dbt creates "fake" temp tables when the `create_table_as()` macro is called with `temporary=True. These are real permanent tables that are set to expire after 12 hours:
> 
> https://github.com/dbt-labs/dbt-bigquery/blob/5253bf1579653c3f335de0f2d9e5558a748e7b8b/dbt/adapters/bigquery/impl.py#L711-L713
  
Here I can confirm the temporary table that was created during a failed schema change, had a TTL set on it.
The following full refresh didn't clear the table, but didn't have an issue with it.

I don't see a pressing issue in changing the current behavior in this context - as opposed to the different edge cases that were mentioned in this thread. Let me know if I'm mistaken. Else I'll close the issue shortly.

**Comment by mayansalama** [comment]
Leaving this here as I found this thread while dealing with concurrent loads to bq. This will make the temp table names dynamic, as otherwise they will overwrite each other if DBT is invoked at the same time by seperate processes. We have an event driven pipeline that occasionally runs into this scenario. The downside is that it results in a tonne of temp tables that all stick around for 12 hours, so we added in a post hook to remove them from BQ.

```dynamic_temp_tables.sql
{% macro tmp_suffix() %}
  {{ return("__tmp_" ~ invocation_id[:6]) }}
{% endmacro %}

{% macro make_temp_relation(base_relation, suffix='__dbt_tmp') %}
  {{ return(adapter.dispatch('make_temp_relation', 'dbt')(base_relation, tmp_suffix() )) }}
{% endmacro %}

{% macro incremental_tmp_table_dropper(bigQueryRelationObject) %}
    {%- set tmpTableName -%}
        {{ bigQueryRelationObject.database + '.' + bigQueryRelationObject.schema + '.' + bigQueryRelationObject.identifier + tmp_suffix()}}
    {%- endset -%}
    {% set query %}
        drop table if exists `{{tmpTableName}}`;
    {% endset %}

    {{ return(query) }}
{% endmacro %}
```

```dbt_project.yml
models:
  my_project:
    ...
    +post-hook:
      - "{{incremental_tmp_table_dropper(this)}}"
```

**Comment by Fleid** [comment]
Thanks a lot for the workaround @mayansalama 

As a reminder, it's not recommended to run multiple instances of dbt on the same target for exactly these kinds of reasons. Glad you managed to make it work in your case ;)

**Comment by mayansalama** [comment]
For what it's worth we're switching our ingestion pipelines to batch on a cron by default, but agreed there are legitimate usecases for this. One example is that we have many dbt projects that operate independently, however they all use the same audit tables (we use [elementary](https://github.com/elementary-data/elementary)). Is this really an anti pattern? For append only tables it seems safe to me.

**Comment by Fleid** [comment]
@dbeatty10 interesting comments for the incremental materialization!

**Comment by Pujathacker2210** [comment]
Hello, has this been fixed? we are running into similar issue with dbt version 1.7.1.
