### ISSUE TITLE
[CT-618] hours_to_expiration neglected when used with partitions

### ISSUE THREAD

**Issue by MartinNowak** [dbt-labs/dbt-bigquery#185]
### Describe the bug
When creating a new ingestion-time partitioned table, the `hours_to_expiration` option is not processed.

### Steps To Reproduce
```sql
{{
  config(
    partitions=['20190130'],
    hours_to_expiration=1000000,
  )
}}
SELECT 1 AS a
```

### Expected behavior
Should set or update the expiration time of the table.

### System information
**The output of `dbt --version`:**
```
installed version: 0.21.1
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.21.1
  - bigquery: 0.21.1
```

**The operating system you're using:**
linux

**The output of `python --version`:**
3.10

**Comment by McKnight-42** [comment]
@MartinNowak thank you for wanting bringing this up, sometime before we released `1.0.0` for `dbt-core` and the adapter plugins we decided to remove the logic around time-ingested partitioned tables for BigQuery as it going to be deprecated see [#42](https://github.com/dbt-labs/dbt-bigquery/pull/42) the default functionality has hung around slightly longer than anticipated but we have another contributor who is currently working on a way to provide the same functionality via sql only [#167](https://github.com/dbt-labs/dbt-bigquery/pull/167) not relying on the old BigQuery method which would allow it to remain post the final deprecation. They also have a few other PR's in the same vein that might be an interest to you.

as for now you still have the ability to swap to [ column-based partitioning for table](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#partition-clause).

if you have any more questions please feel free to ask and I will do my best to try help!
