### ISSUE TITLE
DBT + Bigquery : 404 Not found: Dataset hello-data-pipeline:staging_benjamin was not found in location EU

### ISSUE THREAD

**Issue by go-east** [dbt-labs/dbt-bigquery#19]
### Describe the bug

**When doing "DBT run" with this script**

```
{{ config(materialized='table') }}

SELECT customer_id FROM `hello-data-pipeline.adwords.google_ads_campaign_stats` 
```

**I get the following error**

```
15:41:51 | 2 of 3 START table model staging_benjamin.yo......................... [RUN]
15:41:51 | 2 of 3 ERROR creating table model staging_benjamin.yo................ [ERROR in 
0.32s]
Runtime Error in model yo (models/yo.sql)
404 Not found: Dataset hello-data-pipeline:staging_benjamin was not found in location EU
(job ID: 4020ce42-ec44-438e-8ea0-9f4fe4adcc8c)
```

_NB. Bigquery does not show any error when doing this query in Bigquery Editor. 
NB 2 DBT does not show any error when "running sql" command directly in the script editor
NB3 : No error when doing db run with example or with a public big query like this 

```
{{ config(materialized='table') }}
SELECT *
FROM 'bigquery-public-data.stackoverflow.posts_questions'
ORDER BY view_count DESC
LIMIT 1
```

_

### Steps To Reproduce

- Create a bigquery project
- Go to a bigquery table and click on "query table"
- Take the Select and From Statement automatically generated
- Create a DBT model and paste your code in your DBT model
- DBT RUN

### Expected behavior
It should DBT run without error.. 

### System information
**Which database are you using dbt with?**
BIG QUERY

**The operating system you're using:**
DBT CLOUD

**Others**
Data imported from FIVETRAN

**Comment by kmclaugh** [comment]
FYI when this happened to me I had to delete my dev dataset `dbt_kmclaughlin` in Big Query directly AFTER updating the location (in dbt cloud in my case). Only then did `dbt run` work.

**Comment by sangirawat** [comment]
In my case, the location of source dataset is EU , but destination dataset has to be europe-west1, dbt is giving me this error. Is it not possible to copy EU to europe-west1?

**Comment by WesleyBLDC** [comment]
Having the same issue, did anyone else find a fix for this?

Beyond what this person said? Because this sounds pretty tedious for a lot of tables

Had the same issue and my fix was:

create the table manually in BigQuery, choosing the right region
delete the table
run dbt model that creates the table
Tada, it works automagically.
