### ISSUE TITLE
[CT-686] support kms_key_name for seeds

### ISSUE THREAD

**Issue by b0lle** [dbt-labs/dbt-bigquery#191]
### Describe the feature
Support kms_key_name for seeds. Its only supported for models at the moment - see [docs](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#managing-kms-encryption).

### Describe alternatives you've considered
I tested the feature with models and snapshots, which worked fine:
```
# dbt_project.yml

...

models:
  my_project:
    +kms_key_name: projects/gcp_project_name/locations/europe/keyRings/bq_dataset/cryptoKeys/public

snapshots:
  my_project:
    +kms_key_name: projects/gcp_project_name/locations/europe/keyRings/bq_dataset/cryptoKeys/public
```

There seems to be no effect an seed data:
```
# dbt_project.yml

...

seeds:
  my_project:
    +kms_key_name: projects/gcp_project_name/locations/europe/keyRings/bq_dataset/cryptoKeys/public
```

### Who will this benefit?
Everyone who uses seeds and bigquery customer managed keys.

### Are you interested in contributing this feature?
It would be a pleasure to contribute. Please give me a hint which modules handles seed table creation and where to start.

**Comment by McKnight-42** [comment]
@b0lle Thank you this idea and putting in the pr will take a look!
