### ISSUE TITLE
[CT-692] Enrich the adapter response to analyze executed BigQuery jobs in detail

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-bigquery#194]
### Describe the feature
We are able to get `bytes_processed` with adaptor responses. 
We put `total_bytes_processed` to the adaptor response. So, we are able to estimate cost of a query with `results.adapter_response["bytes_processed"]` in `run_results.json`.
When a BigQuery user takes advantage of the flat fare plan, consumed slots milliseconds is more important to improve resource allocation. So, it would be great to enrich the adapter resource by adding `slot_millis` and so on. By doing that, we can analyze executed BigQuery queries by dbt in detail.

https://github.com/dbt-labs/dbt-bigquery/blob/1.1.latest/dbt/adapters/bigquery/connections.py#L86-L88

### Describe alternatives you've considered
I am not sure if we are able to get something like `slot_mills` of the `QueryJob` class from dbt artifacts. 

### Who will this benefit?
People who want to analyze executed queries by dbt in detail

### Are you interested in contributing this feature?
I would love to implemented the feature.

**Comment by jtcohen6** [comment]
Makes a lot of sense to me @yu-iskw! Thanks for clearly laying out the issue, and opening the accompanying PR.
