### ISSUE TITLE
Remove ingestion-time partitioned tables in BigQuery and all associated logic

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-bigquery#20]
### Describe the feature
dbt's support for "ingestion-time" partitioned tables is a relic of BigQuery's historical lack of support for table partitioning DDL. BigQuery has supported column-level partitioning for some time now, so we should remove the largely-unused ingestion-time partitioning table logic from dbt.

Methods to remove:
 - [impl._materialize_as_table](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/plugins/bigquery/dbt/adapters/bigquery/impl.py#L392)
 - [impl._materialized_as_view](https://github.com/fishtown-analytics/dbt/blob/dev/octavius-catto/plugins/bigquery/dbt/adapters/bigquery/impl.py#L377)
 - [impl.execute_model](https://github.com/fishtown-analytics/dbt/blob/51278c0fbf5ba8e0333befdf3dd9f9cd9949fe54/plugins/bigquery/dbt/adapters/bigquery/impl.py#L479)
 - [connections.create_bigquery_table](https://github.com/fishtown-analytics/dbt/blob/51278c0fbf5ba8e0333befdf3dd9f9cd9949fe54/plugins/bigquery/dbt/adapters/bigquery/connections.py#L252)
 - [connections.create_view](https://github.com/fishtown-analytics/dbt/blob/51278c0fbf5ba8e0333befdf3dd9f9cd9949fe54/plugins/bigquery/dbt/adapters/bigquery/connections.py#L269)
 - [connections.create_table](https://github.com/fishtown-analytics/dbt/blob/51278c0fbf5ba8e0333befdf3dd9f9cd9949fe54/plugins/bigquery/dbt/adapters/bigquery/connections.py#L276)
 - [connections.create_date_partitioned_table](https://github.com/fishtown-analytics/dbt/blob/51278c0fbf5ba8e0333befdf3dd9f9cd9949fe54/plugins/bigquery/dbt/adapters/bigquery/connections.py#L291)
 - [macro: make_date_partitioned_table](https://github.com/fishtown-analytics/dbt/blob/51278c0fbf5ba8e0333befdf3dd9f9cd9949fe54/plugins/bigquery/dbt/include/bigquery/macros/materializations/table.sql#L1-L27) + all associated materialization logic

As a part of this change, we should also remove the BigQuery-specific `timeout_seconds` config, which is only used as a part of creating ingestion-time partitioned tables via the BigQuery HTTP API. We should consider supporting a dbt-wide `timeout_seconds` config in the future (this would apply to any query invoked by dbt), so let's continue to support the config in `profiles.yml`, but render a warning at run-start indicating that the config is not used.

> Warning: The configured target specifies a timeout_seconds config, which is currently unused. Support for this config may be removed in a future release of dbt.

### Additional context
BQ-only... we should be able to delete a whole lot of code!

### Who will this benefit?
dbt maintainers/contributors, users who (rightfully) misunderstand the nature of the `timeout_seconds` config

**Comment by hui-zheng** [comment]
@leahwicz and @jtcohen6,

I saw #42 is just opened. 

Is the `timeout_seconds` above already implemented, or Is it something to be done in the future?

**Comment by jtcohen6** [comment]
@hui-zheng My only intent with #42 is to remove the logic specific to ingestion-time partitioned tables. It hasn't been a feature with first-class support for some time, nor is it the recommended way to create partitioned tables on BigQuery.

Let's open a separate issue for widening the scope of `timeout_seconds`. Following the proposal above:
- We could implement this, on a run level, for BigQuery specifically, via a `profiles.yml` config
- We could implement this across all database adapters, as a "global" config, via flag + env var + `profiles.yml` config. Then it's up to each database adapter to pull that global config into their own `connections.py` logic
- We could implement this on a per-node level, as a resource config. This approach doesn't feel quite right to me today.

What do you think? My sense is that this isn't BigQuery-specific, but more generally applicable across many databases. If that's the case, the right place for the new issue would be in the `dbt-core` repo.

**Comment by txomon** [comment]
We are big users of ingestion time partitioned tables and were wondering where this table came from

> nor is it the recommended way to create partitioned tables on BigQuery

@jtcohen6 would you mind pointing out to what part of the documentation speaks about this?

**Comment by jtcohen6** [comment]
@txomon It's true that ingestion-based partitioned tables have stuck around for longer than we anticipated, and they still have some net advantages over column-based partitioned tables. The way in which they were supported in dbt before v1.0 was still at odds with most other modeling abstractions.

Check out some newer issues (and a draft PR) to add these capabilities back into dbt, in ways that are more aligned with existing paradigms for incremental modeling: #75, #77, #136
