### ISSUE TITLE
BigQuery labels on schemas/dataset

### ISSUE THREAD

**Issue by shedd** [dbt-labs/dbt-bigquery#22]
### Describe the feature
We use labels on Google Cloud assets for inventory tracking purposes. For our Bigquery datasets, we need labels at the schema/dataset level.

It looks like it's possible to add other Bigquery schema-level configuration to the profile - e.g. [dataset location](https://github.com/fishtown-analytics/dbt/issues/969).

Are there any plans to support labels at the dataset level?

### Describe alternatives you've considered
We tested table-level labels implemented as per dbt-labs/dbt#1942 but our inventory tracking service (Vanta for SOC2 purposes) expects the labels at the dataset level.

### Who will this benefit?
Other Bigquery users who are working with labels at the dataset level.

**Comment by sparrovv** [comment]
Hey there,

Eventually this problem was solved with this macro:

```
{% macro update_dataset_labels(dataset_name, project) %}

   {% set update_labels_query %}
        ALTER schema `{{project}}`.{{dataset_name}}
        SET OPTIONS (
            labels=[("foo-name", "foo-value")]
        )
   {% endset %}

   {% set get_labels %}
        SELECT
            option_value
        FROM
            `{{project}}`.INFORMATION_SCHEMA.SCHEMATA_OPTIONS
        WHERE
          schema_name="{{dataset_name}}"
          and option_name="labels"
  {% endset%}

  {% do run_query(update_labels_query) %}
  {% set result =  run_query(get_labels).columns[0].values() %}
  {% do log(result, True) %}

{% endmacro %}
```

```
 dbt run-operation update_dataset_labels --args '{"dataset_name": "dbt_test", "project": "foo"}'
```

Tha macro could be made more generic, and source labels from the project.yml, but for the time being it works as expected.

**Comment by BenHizak** [comment]
@sparrovv this is great. Thank you 👍

**Comment by BenHizak** [comment]
Is there any plan to make this native functionality (without a macro) in DBT?
