### ISSUE TITLE
[CT-892] Testing account setup for python model(GCP dataproc)

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-bigquery#233]
### Describe the feature
We are adding python model here via Dataproc. It requires a dataproc service enabled in the testing GCP account to run. We will probably also need to implement something to start/stop the cluster when we run the action so we don't pay a cluster 24/7. Or this could be something to setup in the cluster

### Additional context
This is not top priority but require someone with GCP experience and GHA experience to setup

### Who will this benefit?
Functional tests for python model

**Comment by jtcohen6** [comment]
@ChenyuLInx Good point!

For managed clusters, we might have a couple options:
- https://cloud.google.com/dataproc/docs/guides/dataproc-start-stop
- https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling (though the docs say: "Autoscaling is not recommended for the purpose of scaling a cluster down to minimum size when the cluster is idle," and encourages the use of Workflows or Scheduled Deletion instead)

Based on some back-of-envelope math ($0.01 per vCPU per hour, https://cloud.google.com/dataproc/pricing), running a single-node cluster uninterrupted for 24 hours would cost about $1, so $30 per month. But there are also services that Dataproc depends on, and it looks like those are billed separately.

Users are going to run into this same limitation. (Depending on their organization, a few hundred dollars a month is either a lot, a little, or virtually nothing.) IMO all the more reason for us to take another look at Dataproc Serverless / Batches (https://cloud.google.com/dataproc-serverless/docs/overview). The initial setup may be more of a bear, but if it's one-time setup only, that's far preferable to requiring users to manage persistent infrastructure (either within or outside of dbt).
