### ISSUE TITLE
[CT-904] Add test integration test for BigQuery-specific adapter_response contents

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-bigquery#235]
### Describe the feature
a BigQuery specific set of integration/functional tests to check the adapter response contents would be great to double check build of contents and verify new feature adds such as 
- https://github.com/dbt-labs/dbt-bigquery/pull/195
- https://github.com/dbt-labs/dbt-bigquery/issues/92

### Who will this benefit?
users/maintainers will all have viable ways to trust the bigquery adapter_response

**Comment by jtcohen6** [comment]
Thanks for opening @McKnight-42!

I added a test to `dbt-snowflake` that does something similar, by inspecting the `results` object to ensure the expected value of `adapter_response["rows_affected"]`: https://github.com/dbt-labs/dbt-snowflake/blob/main/tests/functional/adapter/test_incremental_run_result.py
