### ISSUE TITLE
[BQ] Google service account authentication failure when running dbt tests

### ISSUE THREAD

**Issue by cyrus-cherre** [dbt-labs/dbt-bigquery#25]
### Describe the bug
When running dbt tests in a container, I intermittently receive authentication errors, which cause the running tasks to fail.

### Steps To Reproduce
1. Use oauth authentication in the bigquery profile, and set threads to 2
2. In a containerized environment using a gcloud service account for authentication (as opposed to env var GOOGLE_APPLICATION_CREDENTIALS) run `dbt test [my_model]` (Expect ~288 tests to run)

### Expected behavior
I expect all tests to succeed (verified by running locally). 

### Screenshots and log output
1. log (without --debug)
![image](https://user-images.githubusercontent.com/58487646/105764278-bd0ae000-5f24-11eb-8fe0-82458cbc3b25.png)

2. example stack trace
```
"exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py\", line 206, in open\n    handle = cls.get_bigquery_client(connection.credentials)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py\", line 187, in get_bigquery_client\n    creds = cls.get_bigquery_credentials(profile_credentials)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py\", line 157, in get_bigquery_credentials\n    credentials, project_id = google.auth.default(scopes=cls.SCOPE)\n  File \"/usr/local/lib/python3.7/site-packages/google/auth/_default.py\", line 354, in default\n    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)\ngoogle.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/dbt/task/base.py\", line 333, in safe_run\n    result = self.compile_and_execute(manifest, ctx)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/task/base.py\", line 276, in compile_and_execute\n    result = self.run(ctx.node, manifest)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/task/base.py\", line 378, in run\n    return self.execute(compiled_node, manifest)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/task/test.py\", line 84, in execute\n    failed_rows = self.execute_schema_test(test)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/task/test.py\", line 64, in execute_schema_test\n    fetch=True,\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/base/impl.py\", line 227, in execute\n    fetch=fetch\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py\", line 275, in execute\n    query_job, iterator = self.raw_execute(sql, fetch=fetch)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py\", line 248, in raw_execute\n    client = conn.handle\n  File \"/usr/local/lib/python3.7/site-packages/dbt/contracts/connection.py\", line 71, in handle\n    self._handle.resolve(self)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/contracts/connection.py\", line 96, in resolve\n    return self.opener(connection)\n  File \"/usr/local/lib/python3.7/site-packages/dbt/adapters/bigquery/connections.py\", line 210, in open\n    gcloud.setup_default_credentials()\n  File \"/usr/local/lib/python3.7/site-packages/dbt/clients/gcloud.py\", line 24, in setup_default_credentials\n    run_cmd('.', [\"gcloud\", \"auth\", \"application-default\", \"login\"])\n  File \"/usr/local/lib/python3.7/site-packages/dbt/clients/system.py\", line 436, in run_cmd\n    out, err)\ndbt.exceptions.CommandResultError: Got a non-zero returncode running: ['gcloud', 'auth', 'application-default', 'login']"
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
```

**The operating system you're using:**
![image](https://user-images.githubusercontent.com/58487646/105763337-aadc7200-5f23-11eb-9161-e294c8f30e41.png)

**The output of `python --version`:**
```
Python 3.7.7
```

### Additional context
1. Using gcloud service account, not GOOGLE_APPLICATION_CREDENTIALS
2. Note that prior to seen error, more than 150 tests PASS. Eventually, they start passing again.

**Comment by MehdiDRISSIB** [comment]
I had the same problem. 

Install in your machine Google Cli
And
Run this command: gcloud auth application-default login

It works for me.

**Comment by rahfaeu-bk** [comment]
I ran that last command sugested: `gcloud auth application-default login`

But I am getting the following warning message, must i worry about?

> WARNING:
> Cannot add the project "dp-c360-prd" to ADC as the quota project because the account in ADC does not have the "serviceusage.services.use" permission on this project. You might receive a "quota_exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.
