### ISSUE TITLE
[CT-1033] [Enhancement] Apply all dataset access grants for authorized views at run end, in main thread

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-bigquery#267]
### Describe the feature

"Batch up" all dataset access grants to the end of an invocation, similar to the discussion in https://github.com/dbt-labs/dbt-bigquery/issues/87#issuecomment-1157408966. This is much faster / more efficient, and avoids thread-safety issues — but at the cost of significant potential delay between when each view is (re)created, and when their access is authorized (all at once, after every model has run).

Big idea:
- At run end, identify all authorized views that have been created during the run
- Batch up into a set of mappings between `{dataset_to_grant_access_on: [views_needing_access]}`
- Make API call to apply grants, once per dataset, for all datasets in sequence

There's some pseudo-code outlining this in https://github.com/dbt-labs/dbt-bigquery/issues/87#issuecomment-997025191. Of course, we'd want to write that logic in Python. We might need a new task/run-level "hook," similar to `adapter.post_model_hook`.

### Describe alternatives you've considered
Provide thread-safety by other means, e.g. moving the logic into `adapter.post_model_hook` (instead of [view materialization](https://github.com/dbt-labs/dbt-bigquery/blob/2c4041752d556b57f0e15f8711c950a7c296f0b9/dbt/include/bigquery/macros/materializations/view.sql#L21-L25)) and holding a lock.

Update: This is what's proposed in https://github.com/dbt-labs/dbt-bigquery/pull/265

### Additional context
- https://cloud.google.com/bigquery/docs/share-access-views
- https://docs.getdbt.com/reference/resource-configs/bigquery-configs#authorized-views

Not to be confused with standard `grants`!

### Who will this benefit?
Users of multiple authorized views on `dbt-bigquery`

### Are you interested in contributing this feature?
Definitely open to a community contribution!

**Comment by judahrand** [comment]
Even as a temporary step is there something wrong with the approach in #265? It should prevent the access updates from colliding at the expense of slowing things down with locking.
