### ISSUE TITLE
dbt deps on BigQuery requires either gcloud auth or "project" set

### ISSUE THREAD

**Issue by max-sixty** [dbt-labs/dbt-bigquery#27]
### Describe the bug & Steps To Reproduce

Running `dbt deps` with a `profiles.yml` which a) doesn't have a project and b) in an environment without a valid gcloud auth (such as a docker build):

```
nimbus:
  target: user
  outputs:
    user:
      type: bigquery
      method: oauth
      dataset: my-dataset
      timeout_seconds: 3600
      threads: 24
      # project: my-project
```

Raises an error:

```
 => ERROR [dev 11/12] RUN dbt deps                                                                                                                                           5.2s
------
 > [dev 11/12] RUN dbt deps:
dbt-labs/dbt#36 1.615 Running with dbt=0.19.0
dbt-labs/dbt#36 4.925 Encountered an error:
dbt-labs/dbt#36 4.925 Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
------
executor failed running [/bin/sh -c dbt deps]: exit code: 2
```

These works:
- Running with the `project:` uncommented
- Running with `dbt deps --target=null`

### Expected behavior

Does `dbt deps` need the database / project name at that stage? If so, this is the correct behavior. But if not, there's no need to break in a docker build.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.19.0

Up to date!

Plugins:
  - bigquery: 0.19.0
  - snowflake: 0.19.0
  - redshift: 0.19.0
  - postgres: 0.19.0
```

**The operating system you're using:**
MacOS

**The output of `python --version`:**
Python 3.8.8

**Comment by veriahn** [comment]
I get the same issue when I run dbt compile
While I have authenticated my terminal using gcloud auth login, when I run dbt compile, I get 

06:25:06  Running with dbt=1.1.1
06:25:06  Found 12 models, 2 tests, 0 snapshots, 0 analyses, 668 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
06:25:06
06:25:06  Encountered an error:
Database Error
  Runtime Error

    dbt encountered an error while trying to read your profiles.yml file.

    Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
