### ISSUE TITLE
[CT-1069] incremental predicates for merge strategy

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-bigquery#283]
### Describe the feature
Allow users to supply arbitrary incremental predicates to incremental models to improve performance

see [core issue here ](https://github.com/dbt-labs/dbt-core/issues/5680)

### Who will this benefit?
Incremental model users with large data sets

### Are you interested in contributing this feature?
oh yeah baby

**Comment by lostmygithubaccount** [comment]
@dave-connors-3 thanks for opening this and the PR! I've marked the PR as ready_for_review, hopefully it is picked up soon :)
