### ISSUE TITLE
[CT-1071] Macro which returns the largest partition of a table

### ISSUE THREAD

**Issue by judahrand** [dbt-labs/dbt-bigquery#286]
### Describe the feature

A macro which uses the `INFORMATION_SCHEMA` to return a literal defining the maximum partition of an incremental model to avoid having to query `{{ this }}` in an `if is_incremental()` block.

### Who will this benefit?
People who have large incremental models.

### Are you interested in contributing this feature?
Yup.

**Comment by dbeatty10** [comment]
Thanks for opening this issue and the corresponding pull request in https://github.com/dbt-labs/dbt-bigquery/pull/285!

Continuing the discussion in the PR.

**Comment by marcusinthesky** [comment]
Awesome! Great minds . I see there is good progress here, https://github.com/dbt-labs/dbt-bigquery/pull/285/files. It just wasn't named as I expected when I searched.

**Comment by judahrand** [comment]
I'd kinda forgotten about this PR 🤣

**Comment by judahrand** [comment]
Not stale
