### ISSUE TITLE
[CT-1139] Grants need to be explicitly overwritten in order to remove access

### ISSUE THREAD

**Issue by domzae** [dbt-labs/dbt-bigquery#299]
### Describe the bug
After a grant is applied to a model, rerunning the model without a grant causes the permission binding to still exist.

### Steps To Reproduce
1. Add a grant to a model:
```
# dbt_project.yml
models:
  test:
    +schema: test
    +grants:
      roles/bigquery.dataViewer: ['user:<someuser@domain>']
```
2. Run the model `dbt run -s test`. (Observe that the permission is correctly applied to the table) 
3. Remove the grant
```
# dbt_project.yml
models:
  test:
    +schema: test
```
4. Run the model `dbt run -s test`.
5. Observe that permission is still applied to the table

Current workaround: To remove the permission, one must rerun the model with an empty principle list:
```
# dbt_project.yml
models:
  test:
    +schema: test
    +grants:
      roles/bigquery.dataViewer: []
```
### Expected behavior
After steps 1-4, the table should no longer have the previously applied permission.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.0
  - latest:    1.2.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.2.0 - Up to date!
```

**The operating system you're using:**
MacOS 12.2.1
**The output of `python --version`:**
```
Python 3.9.11
```
### Additional context
Not sure if this is BigQuery specific or applies to all adapters.
I guess this is difficult to solve, as dbt needs to know about the permissions it previously granted. At a minimum, this limitation should be documented!

**Comment by jtcohen6** [comment]
Hey @domzae, thanks for opening - we thought about this in the implementation!

If the `grants` config isn't specified for a model — the config is completely empty/missing — dbt will take that to mean that you don't want it managing grants for that model. It will ignore grants entirely, and run zero `grant` or `revoke` statements. This is to account for users who want to leave default grants in place, or manage grants with other tools.

If you instead _update_ the `grants` config to include zero recipients, dbt will run a `revoke` statement to remove any grants currently in place on the table. It looks like you figured this out:

> Current workaround: To remove the permission, one must rerun the model with an empty principle list:

This isn't a workaround, but in fact the current intended behavior.

> At a minimum, this limitation should be documented!

Agreed!! I took a quick look in our docs, and I couldn't find a clear reference to this: https://docs.getdbt.com/reference/resource-configs/grants#general-examples

So I think the next step here will be to open an issue in the docs repo to make this behavior clearer.
