### ISSUE TITLE
[CT-1181] Fix bot changelog generation

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-bigquery#309]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Changelog generated by bot-changelog.yml has the following bugs

- does not correctly select label
- adds a newline to the changelog that causes tests to fail
- runs twice on opened PRs

- Please verify that this is not happening in other repos.

### Expected Behavior

All tests pass and it runs a single time for the correct label.

### Steps To Reproduce

Look at a PR from dependabot.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```

### Additional Context

The changes were made in dbt-core [here](https://github.com/dbt-labs/dbt-core/pull/5754). The same changes can be made here. This includes updating the version of the marketplace action that is being used.

**Comment by martynydbt** [comment]
This is so old. We have made so many changes since then, if it comes back we will address it.
