### ISSUE TITLE
[CT-1214] [Feature] Enable pandas-on-Spark DataFrames for BigQuery

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-bigquery#316]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Re-implement the [solution for dbt-spark](https://github.com/dbt-labs/dbt-spark/pull/469) and dbt-databricks into dbt-bigquery.

### Describe alternatives you've considered

- Not supporting pandas-on-Spark DataFrames for BigQuery

### Who will this benefit?

Users with pandas-on-Spark DataFrames

### Are you interested in contributing this feature?

✅ Yep

**Comment by jtcohen6** [comment]
Copying from comment here: https://github.com/dbt-labs/dbt-spark/pull/469/files#r975677401

Pandas-on-PySpark was introduced in Spark v3.2, and latest Dataproc images are still on Spark v3.1: https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.0
