### ISSUE TITLE
[CT-1331] [Feature] Add metadata to a model without running the model

### ISSUE THREAD

**Issue by nolan-jardine** [dbt-labs/dbt-bigquery#348]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The ability to add metadata (descriptions, policy tags) to a model as defined in a `.yml` file without running the model or needing the corresponding `.sql` file (in the case of objects not created through dbt).

For our main use case, we have CDC processes running that create tables, load data, and modify table schemas as they evolve in the source database (eg. columns being added, etc.). It would be very nice to have a way to add metadata to tables that were not directly created through dbt.

### Describe alternatives you've considered

The workarounds for this that we've been using are:

- For models created through dbt - Re-run the whole model
_This is not ideal because it may be reprocessing data unnecessarily_
- For models not created through dbt - Create a trivial `.sql` file that does not load any data. Example:
```
    {{ config(materialized='incremental') }}

    SELECT * FROM {{ this }} WHERE false
```
_This was not ideal because it's repetitive code that needs to be added for every object. Also not ideal because this will still process data in BigQuery and increase costs_
- Using Terraform to add policy tags
_This was not a viable solution because Terraform requires the entire table schema to be defined. This is a problem because if the table schema is modified by an external process, Terraform will drop and recreate the table to get it back to its defined schema._

### Who will this benefit?

Anybody that wants to manage all their metadata (including policy tags) with one tool.

### Anything else?

BigQuery policy tags in dbt: https://docs.getdbt.com/reference/resource-configs/bigquery-configs#policy-tags

**Comment by jtcohen6** [comment]
Hey @nolan-jardine, I totally hear the ask here. There's a past issue that seems relevant to this request: https://github.com/dbt-labs/dbt-core/issues/4226

To summarize the discussion over there: It's probably possible, as a one-off operation, to perform the metadata updates you have in mind. That's a workaround that still enables you to define this metadata in dbt `.yml` files, and take advantage of its underlying constructs (models, BigQuery API requests, ...). We're less likely to support this natively as a first-class dbt pattern in the near term.

That said, I have heard this story before:

> For our main use case, we have CDC processes running that create tables, load data, and modify table schemas as they evolve in the source database (eg. columns being added, etc.).

Could you say a bit more about what processes are updating those tables, and the handoff between those processes (loading/modifying the data) and dbt (defining the metadata)? Could you imagine wanting to orchestrate those CDC processes via dbt in the future?
