### ISSUE TITLE
Bigquery model-level unique tests on concat() columns

### ISSUE THREAD

**Issue by Dimi727** [dbt-labs/dbt-bigquery#35]
Hi everyone. 

I did not find this issue anywhere yet which seems odd to me and I dont know if it is on my side.

Using Bigquery and `dbt 0.20.2`.

Having defined a test for a model like this:
```yml
  - name: base_test_model
    tests:
      - unique:
          column_name: "concat(id, field, changed_at)"
```
Which was working before `dbt 0.20.0`. Now I get an error:
> Database Error in test unique_base_test_id_field_changed_at (models\base\schema.yml)
>   SELECT list expression references column id which is neither grouped nor aggregated at [12:5] compiled SQL at

I checked in projects where I use `dbt 0.19.x` and the test above compiled to this:
```sql
select count(*) as validation_errors
from (

    select
        concat(id, field, changed_at)

    from base_test
    where concat(id, field, changed_at) is not null
    group by concat(id, field, changed_at)
    having count(*) > 1

) validation_errors

```

Now it compiles to this:
```sql
select
      count(*) as failures
    from (
      
    
select
    concat(id, field, changed_at) as unique_field,
    count(*) as n_records

from base_test
where concat(id, field, changed_at) is not null
group by concat(id, field, changed_at)
having count(*) > 1

    ) dbt_internal_test
```

which Bigquery seems not to like. Using the query above and removing the alias `unique_field` works for Bigquery.

With Postgres and MySQL both of the above queries run. Did not test Snowflake and Redshift.

**Comment by jtcohen6** [comment]
Resolved by #10
