### ISSUE TITLE
[CT-1454] [Bug] dbt-bigquery 1.3.0 compatibility issue with apache-airflow-providers-google

### ISSUE THREAD

**Issue by driazanova** [dbt-labs/dbt-bigquery#370]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I want to use last version of dbt==1.3.0 with my Airflow, I have Airflow version 2.4.2, and dbt-core==1.3.0. I also need to install apache-airflow-providers-google to work with GCP. 
Tried to install with docker container and locally, same behaviour.

### Expected Behavior

There is no issue with previous version of dbt and airflow:
apache-airflow==2.2.2
apache-airflow-providers-google==8.4.0
dbt-core==1.2.0
dbt-bigquery==1.2.0
 

So I'm expecting to fix this dependencies with new one.

### Steps To Reproduce

here it is list with my requirements:
apache-airflow==2.4.2
apache-airflow-providers-google==8.4.0
dbt-core==1.3.0
dbt-bigquery==1.3.0

### Relevant log output

```shell
The conflict is caused by:
    apache-airflow-providers-google 8.4.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
```

### Environment

```markdown
- OS: macOS Monterey, Linux version 5.15.64-0-virt (buildozer@build-3-16-aarch64) (gcc (Alpine 11.2.1_git20220219) 11.2.1 20220219, GNU ld (GNU Binutils) 2.38) #1-Alpine SMP Mon, 05 Sep 2022 08:02:49 +0000
- Python: 3.9.6
- dbt: 1.3.0
- Airflow: 2.4.2
- dbt-bigquery: 1.3.0
```

**Comment by lostmygithubaccount** [comment]
hi @driazanova, per this similar issue/discussion: https://github.com/dbt-labs/dbt-core/issues/6128#issuecomment-1295624967 I'm going to close this as won't fix -- the latest version of dbt does support the latest version of Airflow, and we feel that's the best we can guarantee at this point

I'd recommend for the `apache-airflow-providers-google` to similarly upgrade to the most recent version of airflow. we are looking to loosen our dependencies in general, but it's not something we'll want to track in individual tickets here

**Comment by driazanova** [comment]
hi @lostmygithubaccount the problem here, I've tried with the latest version of Airflow (2.4.2) and dbt-core 1.3.0. works, but dbt-bigquery 1.3.0. is not compatible with any version with apache-airflow-providers-google. apache-airflow-providers-google 8.4.0 is the latest version for this package. 

The problem here, if I have to work with bigquery I can't do this without apache-airflow-providers-google and it seams that I can't work with dbt-bigquery 1.3.0. in the same time. 

The conflict is caused by:
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 8.4.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 8.3.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 8.2.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 8.1.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 8.0.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 7.0.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.8.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.7.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.6.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.5.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.4.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.3.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 6.2.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-dataproc>=4.0.3
    apache-airflow-providers-google 6.1.0 depends on google-cloud-dataproc<4.0.0 and >=2.2.0
    dbt-bigquery 1.3.0 depends on google-cloud-dataproc>=4.0.3
    apache-airflow-providers-google 6.0.0 depends on google-cloud-dataproc<2.6.0 and >=2.2.0
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 5.1.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 5.0.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 4.0.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 3.0.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 2.2.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 2.1.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 2.0.0 depends on google-cloud-storage<2.0.0 and >=1.30
    dbt-bigquery 1.3.0 depends on google-cloud-storage>=2.4.0
    apache-airflow-providers-google 1.0.0 depends on google-cloud-storage<2.0.0 and >=1.16

**Comment by lostmygithubaccount** [comment]
@driazanova I believe this would then be a bug on `apache-airflow-providers-google` to update to the most recent version of `google-cloud-storage` -- I would suggest opening an issue here per the issue tracker link from their PyPi page: https://github.com/apache/airflow/issues

the airflow packages are not something we have control over, and we do want to keep our dependencies on the latest stable releases

**Comment by Tenzer** [comment]
Note that it's not currently possible to install the latest version of dbt-bigquery by itself either: https://github.com/dbt-labs/dbt-bigquery/discussions/361.
