### ISSUE TITLE
[CT-1525] [Bug] DBT_BIGQUERY_AUTH_METHOD in dev but DBT_BIGQUERY_METHOD in prod

### ISSUE THREAD

**Issue by neilmcguigan** [dbt-labs/dbt-bigquery#399]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

if you look at transform/profiles/bigquery/profiles.yml

in dev, it's
method: "{{ env_var('DBT_BIGQUERY_AUTH_METHOD') }}"

but in staging and prod it's

method: "{{ env_var('DBT_BIGQUERY_METHOD') }}"

these should be consistent

### Expected Behavior

use the same env var name among dev, staging, prod

### Steps To Reproduce

run dbt-bigquery in dev and prod and you'll get an error in prod

### Environment

```markdown
- OS: Ubuntu 20
- Python: 3.8
- dbt-core: latest
- dbt-bigquery: latest
```

**Comment by jtcohen6** [comment]
Hey @neilmcguigan, I think this might be a matter in your own project / deployment, rather than the adapter plugin! Specifically, this file:

> transform/profiles/bigquery/profiles.yml

Isn't defined anywhere in this repo. I'd expect it to be part of your own organization's codebase.
