### ISSUE TITLE
[CT-1606] Issue tracking for BQ PR133 - Seeds parity

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-bigquery#407]
Issue tracking for https://github.com/dbt-labs/dbt-bigquery/pull/133
Solves #125 (not sure why it was closed)

**Comment by nicohein** [comment]
Hi @Fleid ,
I just stumbled across this one as it is a feature we are just looking for and am wondering if you already have an idea in which release this might be included?
Many Thanks
Nico

**Comment by Fleid** [comment]
Hi @nicohein, since it's merged, it should be part of 1.5 :)
