### ISSUE TITLE
[CT-1633] [Feature] Persist docs for sources

### ISSUE THREAD

**Issue by charles-astrafy** [dbt-labs/dbt-bigquery#416]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As per documentation [here](https://docs.getdbt.com/reference/resource-configs/persist_docs), it is mentioned that the "persist_docs" config is not implemented for sources.

Is there a specific reason why it is not implemented for sources ? We would see this as a good feature to be able to persist the documentation of source tables in BigQuery.

### Describe alternatives you've considered

At the moment we either don't put docs on our source tables or do it manually via BigQuery UI.

### Who will this benefit?

Anyone that wants to document its sources in dbt and have the documentations persisted back to BigQuery.

### Are you interested in contributing this feature?

Yes but will need a bit of guidance on where this code is located

**Comment by jtcohen6** [comment]
Hey @charles-astrafy, we've gotten this question before! Check out some of the previous discussions:
- https://github.com/dbt-labs/dbt-core/issues/2540
- https://github.com/dbt-labs/dbt-core/issues/4226
- https://github.com/dbt-labs/dbt-core/issues/6244

From the last one linked above:

> dbt wants to fully manage an object, or not at all. The clarity of that abstraction gets us a lot! Where does this table come from? Whence its properties, its comments, every column it contains? The answer should be either 100% dbt, or zero.

And:

> I do think the right building blocks are in place to code up a custom macro that would handle this.

My attitude here may change, in a future where dbt is more directly responsible for triggering the [staging](https://github.com/dbt-labs/dbt-external-tables) or [ingest](https://github.com/dbt-labs/dbt-core/discussions/5073) of sources. For now, I think the answer given above is still the one I'm going to give.

**Comment by charles-astrafy** [comment]
Hi @jtcohen6 
Thank you for the answer and I agree with the reasoning of why this is not embedded as part of a "dbt" operation.

However we use to define the descriptions for all our tables within dbt (even descriptions for the source tables) so we will work on a macro to be able to persist docs on the source table. This macro can then be run via "run-operation". We think about adding this macro to the codegen package.

**Comment by RRDTIL** [comment]
Sorry for digging this issue out of its grave 😅, @charles-astrafy have you built that macro ? I'm having the same use case haha

**Comment by charles-astrafy** [comment]
Hi @RRDTIL ,

Back in time we did develop a small python script that was taking the property file of dbt sources and then with setting the description in BigQuery with the BQ python client.  We never pushed the code to any dbt packages though.

**Comment by RRDTIL** [comment]
@charles-astrafy thank you for the response !
For the purpose of futur people searching for this, here's what I came with :

```Jinja
{% macro synchronize_descriptions_for_sources() %}
  -- Only executes when dbt is in "execute" mode and not "parse"
  {% if execute %}
    
    {{ log("Starting synchronization of sources descriptions", info=True) }}

    -- Loop over each source in the project
    {% for source_node in graph.sources.values() %}

      -- 1. Sync table description
      -- Assert existence of description
      {% if source_node.description %}

        -- Build Snowflake relation name
        {% set source_relation = source(source_node.source_name, source_node.name) %}
        
        -- Escaping quotes
        {% set table_description = source_node.description | replace("'", "''") %}

        {{ log("Synchronization of descriptions for table : " ~ source_relation, info=True) }}

        -- Build and execute the query to add the comment to the table
        {% set table_comment_sql %}
          COMMENT ON TABLE {{ source_relation }} IS '{{ table_description }}';
        {% endset %}
        {% do run_query(table_comment_sql) %}

      {% endif %}


      -- 2. Synchronize columns descriptions
      -- Loop over each column in source table
      {% for column_node in source_node.columns.values() %}
        -- Assert existence of description for the column
        {% if column_node.description %}

          {% set source_relation = source(source_node.source_name, source_node.name) %}
          {% set column_name = column_node.name %} -- If you want quoting you can change this line to : set column_name = adapter.quote(column_node.name)
          {% set column_description = column_node.description | replace("'", "''") %}

          {{ log("  -> Column : " ~ column_name, info=True) }}

          -- Build and execute the query to add the comment to the column
          {% set column_comment_sql %}
            COMMENT ON COLUMN {{ source_relation }}.{{ column_name }} IS '{{ column_description }}';
          {% endset %}
          {% do run_query(column_comment_sql) %}

        {% endif %}
      {% endfor %}

    {% endfor %}

    {{ log("End of synchronisation for sources descriptions", info=True) }}

  {% endif %}
{% endmacro %}
```
