### ISSUE TITLE
[CT-1723] [Feature] Specify a dataproc Subnetwork in profiles.yml

### ISSUE THREAD

**Issue by dougscc** [dbt-labs/dbt-bigquery#448]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

My Kubernetes clusters are not on the `default` subnetwork, which is resulting in the following error:

`400 Subnetwork 'default' does not support Private Google Access which is required for Dataproc clusters when 'internal_ip_only' is set to 'true'. Enable Private Google Access on subnetwork 'default' or set 'internal_ip_only' to 'false'.`

There is currently no way to specify an alternative network/subnetwork for a submission. Unless I am completely off-base, this might be done using the [compute_v1.types.Subnetwork](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.types.Subnetwork) class.

 I suggest a `dataproc_subnet` dict to be added to the profile, which contains [attributes](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.types.Subnetwork#attributes) used by `Subnets`, which may optionally be supplied to the client when instantiated.

### Describe alternatives you've considered

Can't really think of any. I'm somewhat confused as to why the subnets are not just used as configured by the cluster. This is also an indicator that I may be completely full of baloney and misunderstanding how `DataProcs` works.

### Who will this benefit?

Anyone using a subnet other than `default`.

### Are you interested in contributing this feature?

Willing to give it a shot.

**Comment by dougscc** [comment]
The more I look at this, the more I fear that I am off-base. I am new to the whole kubernetes thing, and am suspecting that this entire idea is completely wrong-headed and is totally due to firewall issues. Unfortunately, I cannot view my firewall settings to even begin thinking clearly about the problem. Feel free to smite me for a fool and close this with prejudice. :)

**Comment by dougscc** [comment]
The more I look at this, the more I fear that I am off-base. I am new to the whole kubernetes thing, and am suspecting that this entire idea is completely wrong-headed and is totally due to firewall issues. Unfortunately, I cannot view my firewall settings to even begin thinking clearly about the problem.

**Comment by jtcohen6** [comment]
I don't believe this is to do with networking requirements for the dbt process, but rather for networking between your Dataproc instance and other GCP resources (namely BigQuery). Docs: https://cloud.google.com/dataproc-serverless/docs/concepts/network

Given the error you're seeing, I think you'll need to configure the network you're using (probably `default`) for the appropriate region here: https://console.cloud.google.com/networking/networks

And edit it to enable "Private Google Access":
<img width="180" alt="Screenshot 2023-01-02 at 11 39 25" src="https://user-images.githubusercontent.com/13897643/210220595-8563422f-8e40-4880-b83d-a60e94a91b45.png">
