### ISSUE TITLE
[CT-1876] [CT-1875] [Feature] Transaction support for hooks in BigQuery

### ISSUE THREAD

**Issue by SSchneider22** [dbt-labs/dbt-bigquery#474]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In dbt core 1.4, only Postgres and Redshift support transactions in hooks, not BigQuery.
https://docs.getdbt.com/reference/resource-configs/pre-hook-post-hook#transaction-behavior

However, BigQuery has recently added support for multi-statement transactions.
https://cloud.google.com/bigquery/docs/reference/standard-sql/transactions

Can you please enable BigQuery to support transactions in hook?

### Describe alternatives you've considered

In hook, add functionality so that BigQuery also supports transactions.

### Who will this benefit?

In BigQuery, it is useful when you want to update data using Insert & Delete, etc.

It is useful when merge by Incremental Model is too slow or cannot be achieved by Incremental Model.

**Comment by Fleid** [comment]
@MichelleArk I see that you assigned this to yourself. I love it :)
Should I remove the triage field though?

**Comment by moxordo** [comment]
If my understanding is correct, the `dbt seed` cmd for Bigquery executes `BigQueryAdapter.drop_relation()` and then `BigQueryAdapter.load_dataframe()` in sequence, without transactions.

I suppose we are subject to the same kind of [race condition issue](https://github.com/dbt-labs/dbt-snowflake/issues/112) that was raised in the [dbt-snowflake repository](https://github.com/dbt-labs/dbt-snowflake/) as well.

Though I'm not certain whether the support for transactions in bigquery hooks will directly handle the issue above, I think it might be a stepping stone for resolving the race condition issue.

Meanwhile, let me know if it is cool to open up an issue for the dbt-bigquery repository as well. Thanks!

**Comment by mirnawong1** [comment]
hey @Fleid , can i confirm that there isn't support for transactions yet?

**Comment by chenme2** [comment]
Hi, can we still have transaction support for BigQuery, currently we can only rely on insert_overwrite, to delete anything that is not partitioned, the DELETE is performed non-atomic way.....

It's a big limitation for us to continue using BigQuery
