### ISSUE TITLE
[CT-1912] [Regression] `require_partition_filter` usage with `insert_overwrite` fails on second run

### ISSUE THREAD

**Issue by github-christophe-oudar** [dbt-labs/dbt-bigquery#483]
### Is this a regression in a recent version of dbt-bigquery?

- [X] I believe this is a regression in dbt-bigquery functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Let's take this simple example:
```
{{
    config(
        materialized = 'incremental',
        incremental_strategy='insert_overwrite',
        partition_by = {
          "field": "hour",
          "data_type": "timestamp",
          "granularity": "hour"
        },
        require_partition_filter = true,
    )
}}
SELECT TIMESTAMP('2023-01-25') as hour, 1 as value
```

If you run it twice it will fail with `"Query error: Cannot query over table '<project>.<dataset>.test_bug' without a filter over column(s) 'hour' that can be used for partition elimination at [39:5]"`

### Expected/Previous Behavior

The query should be successful.

### Steps To Reproduce

Using `dbt-bigquery 1.4.0rc1 (or any 1.4.0)`

Why it fails?
Because the generated code is the following 

```
...
when not matched by source
         and timestamp(timestamp_trunc(DBT_INTERNAL_DEST.hour, hour)) in unnest(dbt_partitions_for_replacement)
        then delete
...
```

instead of

```
...
when not matched by source
         and timestamp_trunc(DBT_INTERNAL_DEST.hour, hour) in unnest(dbt_partitions_for_replacement)
        then delete
...
```

The reason is that BigQuery can't figure out `timestamp(timestamp_trunc(DBT_INTERNAL_DEST.hour, hour))` is the same as `timestamp_trunc(DBT_INTERNAL_DEST.hour, hour)` which means it can't forward the origin of the field (`hour`) to the resulting recreated field. Though we could expect the query planner to do job of inline (and prune) the timestamp cast... it's not the case so we'll have to be smarter when we generate the query to not include it.

### Workaround

Use `"copy_partitions": true` setting such as
```
 partition_by = {
          "field": "hour",
          "data_type": "timestamp",
          "granularity": "hour",
          "copy_partitions": true
        }
```
in 

### Environment

```markdown
- OS:Mac 12.6
- Python: 3.10.9
- dbt-core (working version):1.3.2
- dbt-bigquery (working version): 1.3.0
- dbt-core (regression version): 1.4.0-X
- dbt-bigquery (regression version): 1.4.0-X
```

**Comment by github-christophe-oudar** [comment]
Hello @dbeatty10,
Thanks for looking at it.
I don't think it works in all cases, I think we need to improve the coverage because depending on the partitioning type I'm not sure it would work.
Also I think it doesn't work for instance, with `'data_type': 'date'` because we should use `_PARTITIONDATE` instead `_PARTITIONTIME` for the create table query but let's keep it for another issue 😅

**Comment by anaghshineh** [comment]
Big +1 to this. We upgraded to `dbt-bigquery==1.4.0` and started seeing failures in our incremental models with `require_partition_filter=true`. Thanks @Kayrnt for the quick identification and for putting up a PR.
