### ISSUE TITLE
[CT-1933] [Bug] Time ingestion partitioning doesn't work with `date` data_type

### ISSUE THREAD

**Issue by github-christophe-oudar** [dbt-labs/dbt-bigquery#486]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using `"time_ingestion_partitioning": true` and `"data_type": "date"`, a `dbt run` will fail with following error
```
BadRequest('PARTITION BY expression must be _PARTITIONDATE, DATE(_PARTITIONTIME), DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))')
```

### Expected Behavior

Expected behavior is that the model is created and working as intended.

### Steps To Reproduce

Using following model 
```
{{
    config(
        materialized = 'incremental',
        incremental_strategy='insert_overwrite',
        partition_by = {
          "field": "day",
          "data_type": "date",
          "granularity": "day",
          "time_ingestion_partitioning": true
        }
    )
}}
SELECT DATE('2023-01-25') as day, 1 as value
```

The failure can be reproduced

### Environment

```markdown
- OS: MacOS 12.6
- Python: 3.10.6
- dbt-core: 1.4.0-rc1
- dbt-bigquery: 1.4.0-rc1
```

**Comment by dbeatty10** [comment]
Thanks for opening a PR for this as well @github-christophe-oudar !

**Comment by VersusFacit** [comment]
This issue will not be the end of this saga. This library has lots of edge cases and mutually exclusive DDL elements. To get total coverage, a new issue will need opening.
