### ISSUE TITLE
[CT-1938] [PR Review] Make grant_access_to thread safe #265

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-bigquery#490]
Tracking for:
PR : #265 
Original issue:  #266

**Comment by judahrand** [comment]
@Fleid Are you saying that #265 should be reopened and is a acceptable solution?

**Comment by judahrand** [comment]
Or is #404 the solution which has been accepted?

**Comment by Fleid** [comment]
#404 is the right one
This is just a tracking issue for PRs attached to issues originally tagged as help_wanted.
I just forgot to clean it up. Sorry about the confusion ;)
