### ISSUE TITLE
[CT-2056] [Feature] Support Column-level encryption (AEAD concepts)

### ISSUE THREAD

**Issue by alexandre-rassinoux** [dbt-labs/dbt-bigquery#520]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

To provide a second layer of protection at the column-level for sensitive information (e.g., zip codes), BigQuery proposes to use [Cloud Key Management Service (Cloud KMS)](https://cloud.google.com/kms/docs/concepts) and [AEAD encryption functions](https://cloud.google.com/bigquery/docs/reference/standard-sql/aead_encryption_functions) with Cloud KMS [keysets](https://cloud.google.com/bigquery/docs/reference/standard-sql/aead-encryption-concepts#keysets) or [wrapped keysets](https://cloud.google.com/bigquery/docs/reference/standard-sql/aead-encryption-concepts#wrapped_keysets).

The idea is to enable AEAD encryption directly in dbt when dealing with models, and therefore encrypt or decrypt columns using wrapped keysets.

### Describe alternatives you've considered

It may be possible to create, rewrap or rotate keysets as a pre-processing step outside of dbt, or in a pre-hook (although I am not aware of any way to achieve this in a correct way).

### Who will this benefit?

BigQuery users who may want to encrypt individual values within a table. 
For example, you want to keep data for all of your own customers in a common table, and encrypt each of your customers’ data using a different key.

### Anything else?

Google documentation around AEAD encryption in BigQuery:
[https://cloud.google.com/bigquery/docs/column-key-encrypt](https://cloud.google.com/bigquery/docs/column-key-encrypt)
[https://cloud.google.com/bigquery/docs/reference/standard-sql/aead-encryption-concepts](https://cloud.google.com/bigquery/docs/reference/standard-sql/aead-encryption-concepts)

**Comment by Fleid** [comment]
If I read the documentation correctly, this is not a property of the table/view but rather how you handle the data writing and reading from that table?

```SQL
SELECT
  AEAD.DECRYPT_STRING(
    KEYS.KEYSET_CHAIN(@kms_resource_name, @first_level_keyset),
    ciphertext,
    additional_authenticated_data)
FROM
  ciphertext_table
WHERE
  ...
```

From dbt, what you need is a way to set up the required parameters at the project level, and then be able to reference them in your model.

To me that sounds like [project variables](https://docs.getdbt.com/docs/build/project-variables):
```YAML
name: my_dbt_project
version: 1.0.0

config-version: 2

vars:
  kms_resource_name: '...'
  first_level_keyset: '...'

models:
    ...
```

That can then be used in models:
```SQL
SELECT
  AEAD.DECRYPT_STRING(
    KEYS.KEYSET_CHAIN({{ var('kms_resource_name') }}, {{ var('first_level_keyset') }}),
    ciphertext,
    additional_authenticated_data)
FROM
  ciphertext_table
WHERE
  ...
```.

That is if (big ifs):
- kms_resource_name and first_level_keyset can be serialized as string without breaking everything (no idea if that's the case)
- they are not that secret? We could also load them from [environment variables](https://docs.getdbt.com/reference/dbt-jinja-functions/env_var) (always better), but still

What do you think?

**Comment by alexandre-rassinoux** [comment]
Hello Fleid,

Thank you, and sorry for late reply.

I am not using this mechanism at the moment, but I will try it out as it seems to be a good way of using variables at project level to reuse them in my models.

Thank you again for your help!
