### ISSUE TITLE
[CT-2073] Full compatibility with incremental materialization refactor in v1.3

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-bigquery#523]
Given capacity constraints at the time, we made minimal changes in `dbt-bigquery` for compatibility with the refactor in v1.3:
- https://github.com/dbt-labs/dbt-bigquery/issues/232
- https://github.com/dbt-labs/dbt-bigquery/pull/223

We should add "full" support, akin to what we did in Snowflake:
- https://github.com/dbt-labs/dbt-snowflake/issues/195
- https://github.com/dbt-labs/dbt-snowflake/pull/196

That way:
- users can opt for the explicit `append` strategy
- users can define their own custom strategies (names + macros)

**Comment by singler** [comment]
+1 on the interest of custom incremental strategies.
