### ISSUE TITLE
[Bug] Incremental models on partitioned string column fails

### ISSUE THREAD

**Issue by ivan-fishbrain** [dbt-labs/dbt-bigquery#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given a partitioned on a string column incremental model:
```
{{
    config(
        materialized='incremental',
        partition_by={'field': 'string_column', 'data_type' : 'string'},
        incremental_strategy='insert_overwrite',
    )
}}

SELECT '20201201' AS string_column
```

Running incremental `dbt run` on this model provides erroneous definition of partitions to update. It tries to use non-existent in BigQuery function `string_trunc(string_column, day)` code in `/target/run/` directory:
```
      ...
      -- 2. define partitions to update
      set (dbt_partitions_for_replacement) = (
          select as struct
              array_agg(distinct string_trunc(string_column, day))  -- HERE NON-EXISTENT FUNCTION
          from MODEL_NAME
      );

      
      -- 3. run the merge statement
    merge into 
    ...
    when not matched by source
         and string_trunc(DBT_INTERNAL_DEST.string_column, day) in unnest(dbt_partitions_for_replacement)  -- HERE NON-EXISTENT FUNCTION
        then delete
        ...
```

It causes dbt to fail the run with following error
`Query error: Function not found: string_trunc at [51:34]`

### Expected Behavior

As for dbt version 0.18.2 it ran such model correct:
```
      -- 2. define partitions to update
      set (dbt_partitions_for_replacement) = (
          select as struct
              array_agg(distinct string_column)
          from MODEL_NAME
      );
...
      -- 3. run the merge statement
    merge into MODEL_NAME
    ...

    when not matched by source
         and DBT_INTERNAL_DEST.string_column in unnest(dbt_partitions_for_replacement) 
        then delete

    when not matched then insert
    ...
```

### Environment

```markdown
- OS: MacOS 12.0.1
- Python: 3.8.12
- dbt: official docker image version 0.21.0
```

### What database are you using dbt with?

bigquery

**Comment by ivan-fishbrain** [comment]
@jtcohen6 Thank you for explanation! I wasn't aware about impossibility of creation string-partitioned tables. 
Then, I think dbt should at least create warn about this impossibility explicitly.

**Comment by hugolu-1** [comment]
I think you can partition on anything now. And also under no circumstances should dbt-core be calling a function that's not even supported in bigquery, surely!
