### ISSUE TITLE
[CT-2170] Temporary table not deleted after dbt job finishes running

### ISSUE THREAD

**Issue by sai3563** [dbt-labs/dbt-bigquery#556]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Ok, I'm running a model that goes as follows:

```
{{
    config(
        materialized = 'incremental',
        unique_key = 'id',
        on_schema_change = 'sync_all_columns',
        partition_by = {
          'field': 'created_date',
          'data_type': 'datetime',
          'granularity': 'day'
        },
        require_partition_filter = false,
        incremental_strategy = 'insert_overwrite',
        partitions = ["'2023-02-01'", "'2023-02-02'"]
    )
}}

  SELECT
    *
  FROM
    {{ source(source_schema,source_table) }}
{% if is_incremental() %}
  -- this filter will only be applied on an incremental run
    WHERE date(created_date) in ('2023-02-01', '2023-02-02')
      and updated_date >= '2023-02-20 19:00:01.873000'
{% endif %}
```

Since I am providing partitions, it is using static insert_overwrite method.

It generates a query which goes like this:

```
create or replace table `project`.`target_dataset`.`table_name__dbt_tmp`
    partition by datetime_trunc(created_date, day)
    
    OPTIONS(
      expiration_timestamp=TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 hour)
    )
    as (

-- Use the `ref` function to select from other models

  SELECT
    *
  FROM
    `project`.`source_dataset`.`table_name`
  -- this filter will only be applied on an incremental run
  WHERE date(created_date) in ('2023-02-01', '2023-02-02')
      and updated_date >= '2023-02-20 19:00:01.873000'

    );


merge into `project`.`target_dataset`.`table_name` as DBT_INTERNAL_DEST
        using (

-- Use the `ref` function to select from other models

  SELECT
    *
  FROM
    `project`.`source_dataset`.`table_name`
  -- this filter will only be applied on an incremental run
  WHERE date(created_date) in ('2023-02-01', '2023-02-02')
      and updated_date >= '2023-02-20 19:00:01.873000'
) as DBT_INTERNAL_SOURCE
        on FALSE

    when not matched by source
         and datetime(datetime_trunc(DBT_INTERNAL_DEST.created_date, day)) in (
              '2023-02-01', '2023-02-02'
          )
        then delete

    when not matched then insert
        (`id`, `created_date`, `updated_date`, `status`)
    values
        (`id`, `created_date`, `updated_date`, `status`)
```

As you can see from the above query, there is no `drop table if exists` query running to delete the temporary table. Granted, the table is set to expire in 12 hours, but still, this does not occur when using dynamic insert overwrite & leads to clutter in the target dataset.

The macro for dynamic insert overwrite which is `bq_dynamic_insert_overwrite_sql` does have `drop table if exists {{ tmp_relation }}` in the code which deletes the temporary table.

But the macro for static insert overwrite which is `bq_static_insert_overwrite_sql` doesn't.

### Expected Behavior

The macro for static insert_overwrite should delete the temporary table at the end. Simply adding `drop table if exists {{ tmp_relation }}` in macro  `bq_static_insert_overwrite_sql` would resolve the issue.

### Steps To Reproduce

Run a model with above parameters as described or any model which uses static insert_overwrite method by passing the `partitions` parameter in config.

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt-core: 1.4.1
- dbt-bigquery: 1.4.1
```

### Additional Context

Ready to raise PR for the same. Just need confirmation from someone to proceed.

**Comment by dbeatty10** [comment]
Thanks for opening this and your excellent diagnosis @saimaddali !

Confirmed that you are clear for take-off to open a PR ✈️ 

---

No pressure, but in case you are interested, we actually have a separate issue open related to `bq_static_insert_overwrite_sql`:
- https://github.com/dbt-labs/dbt-bigquery/issues/427

We'd probably want a separate PR for each issue (rather than lumping them both in the same PR).

**Comment by patkearns10** [comment]
The PR fix suggested in https://github.com/dbt-labs/dbt-bigquery/pull/630/files adds a `drop table if exists {{ tmp_relation }}` in macro `bq_static_insert_overwrite_sql` so presumably would resolve this issue as well as https://github.com/dbt-labs/dbt-bigquery/issues/427

**Comment by dbeatty10** [comment]
Thank you @patkearns10 🙌 -- updated https://github.com/dbt-labs/dbt-bigquery/pull/630 to resolve this issue as well.
