### ISSUE TITLE
[CT-2180] [Feature] Add bytes_billed to adapter response

### ISSUE THREAD

**Issue by bruno-szdl** [dbt-labs/dbt-bigquery#560]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

I am working to monitor the BigQuery costs in our projects more efficiently.

Today what dbt returns is `bytes_processed` from job's `total_bytes_processed`, which is **almost** the same as `total_bytes_billed`. The differences, as I know them, are that `total_bytes_billed` is rounded to the nearest MB, and if the query is less than 10MB, `total_bytes_billed` will be 10MB.

So `total_bytes_processed` **is not 100% exactly** what is charged.

**I think `total_bytes_processed` is good for monitoring query performance, and `total_bytes_billed` is good for knowing the real cost.**

You can calculate `total_bytes_billed` from `total_bytes_processed` easily, just apply a couple of rules there. **But if BigQuery already returns the calculated `total_bytes_billed`, there's no point in making this transformation again.**

Besides, this way there's no risk of making a wrong transformation, or the BQ changing some billing rule.

So I would like to add `total_bytes_billed` to the `adapter_response` so we can easily calculate the billing costs.

### Describe alternatives you've considered

It seems very straightforward, just do the same as this PR
https://github.com/dbt-labs/dbt-bigquery/pull/271

But instead of slot time, we want the bytes billed. I think it is a good first issue.

### Who will this benefit?

This would help people calculate the costs of BigQuery queries, by letting BigQuery say the bytes billed, instead of calculating themselves.

### Are you interested in contributing this feature?

Yes, I think I could add bytes_billed to the adapter response.

**Comment by Fleid** [comment]
Hi @bruno-szdl, thanks a lot for the detailed issue, including research for similar prior art :)
This sounds like a good idea and a solid plan.

Removing `triage` and adding `good_first_issue` (equivalent to `help_wanted`).
