### ISSUE TITLE
[CT-2186] Reduce cost for `_dbt_max_partition`

### ISSUE THREAD

**Issue by marcusinthesky** [dbt-labs/dbt-bigquery#564]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Current the `declare_dbt_max_partition` macro actually scans a column in your actual table in order to determine your max partition. For large tables this can be costly and slow. BigQuery has [information tables with partition information](https://cloud.google.com/bigquery/docs/information-schema-partitions) which are cheap and reliable to query. I would recommend a change to the `_dbt_max_partition` function to query the information table:

```
{% macro declare_dbt_max_partition(relation, partition_by, compiled_code, language='sql') %}

  {#-- TODO: revisit partitioning with python models --#}
  {%- if '_dbt_max_partition' in compiled_code and language == 'sql' -%}

    declare _dbt_max_partition {{ partition_by.data_type }} default (
      SELECT
        MAX(PARSE_DATE('%Y%m%d', CAST(partition_id AS STRING)))
        FROM
        `{{ this.schema }}.INFORMATION_SCHEMA.PARTITIONS`
        WHERE table_name = '{{ this.identifier }}'
        AND partition_id IS NOT NULL
    );

  {%- endif -%}

{% endmacro %}

```

**Comment by dbeatty10** [comment]
This makes sense @marcusinthesky ! Thanks for taking the time to notice the problem and thinking of a potential solution 🏅

In this case, there's already an open issue and PR, and I'm going to close this as a duplicate:
- https://github.com/dbt-labs/dbt-bigquery/issues/286
- https://github.com/dbt-labs/dbt-bigquery/pull/285

We would welcome your participation in the threads listed above! It would be nice to get this implemented to eliminate the scan.
