### ISSUE TITLE
[CT-2218] [BigQuery] Implement constraint_support on BigQueryAdapter

### ISSUE THREAD

**Issue by MichelleArk** [dbt-labs/dbt-bigquery#568]
Core issue: https://github.com/dbt-labs/dbt-core/issues/7067

Implement `constraint_support` on the BigQueryAdapter to satisfy:

| constraint type | support       |
|-----------------|---------------|
| not_null        | enforced      |
| primary_key     | supported  |
| foreign_key     | supported  |
| unique          | not supported  |
| check           | not supported |

(from: https://github.com/dbt-labs/dbt-core/issues/7067#issuecomment-1447281379)

Additionally:
- Add the logic for templating out `primary_key` and `foreign_key` constraints within `get_column_spec_ddl`, per [these docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_add_constraint_statement) (see `primary key not enforced` and `references ... not enforced`)
- Remove the `constraints_check` warning raised in `get_columns_spec_ddl`: https://github.com/dbt-labs/dbt-bigquery/blob/main/dbt/include/bigquery/macros/utils/get_columns_spec_ddl.sql#L13-L15

**Comment by amirbtb** [comment]
Hey folks ! Just wanted to inform that GCP announced in the [22/02/2023 Google Cloud release notes](https://cloud.google.com/release-notes#February_22_2023) the beta of **primary & foreign key table constraints**.
Here are the [limitations](https://cloud.google.com/bigquery/docs/information-schema-table-constraints#limitations).

Thank you for this wonderful initiative around constraints (and of course all others) ! ♥️

**Comment by jtcohen6** [comment]
@amirbtb What timing! Thanks for flagging - I updated the description above.
