### ISSUE TITLE
[ADAP-380] [Bug] --full-refresh doesn't work for python models

### ISSUE THREAD

**Issue by mdesnoyer** [dbt-labs/dbt-bigquery#609]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When writing a python dbt model backed by BigQuery, if I change the output model schema (for example by changing the format of the returned DataFrame), then the DataProc job fails with:

1) [Guice/ErrorInCustomProvider]: IllegalArgumentException: BigQueryConnectorException$InvalidSchemaException: Destination table's schema is not compatible with dataframe's schema
  at BigQueryDataSourceWriterModule.provideDirectDataSourceWriterContext(BigQueryDataSourceWriterModule.java:60)
  while locating BigQueryDirectDataSourceWriterContext

This still occurs if I run dbt with --full-refresh

### Expected Behavior

When using full-refresh, I would expect the output table to be dropped before executing the DataProc job, so this kind of error would not happen. 

### Steps To Reproduce

1. Write dbt python job that runs successfully and creates the resulting output table.
2. Change the job to have a different schema (e.g. type change on a column)
3. Run dbt run --full-refresh

### Environment

```markdown
- OS:Ubuntu 20.04
- Python: 3.10.9
- dbt-core: 1.4.1
- dbt-bigquery: 1.4.2
```

**Comment by Fleid** [comment]
I reproduced the issue. I need some time to figure out what is going on there.

**Comment by Fleid** [comment]
Relaying info from the subject matter expert, I'm still investigating.

There is no special logic for dropping models for full refresh here, it reuses the logic for sql. 
The difference in behavior may come from [this](https://github.com/dbt-labs/dbt-bigquery/blame/ea0833424c6445cff853e82ab9a5d563a55d3856/dbt/include/bigquery/macros/materializations/incremental.sql#L108) which probably evaluated to False, so we skipped the dropping part even with full-refresh.

There is a test checking [schema change](https://github.com/dbt-labs/dbt-bigquery/blob/ea0833424c6445cff853e82ab9a5d563a55d3856/tests/functional/adapter/test_python_model.py#L52) that I should continue investigating.

**Comment by mdesnoyer** [comment]
Thank you!
