### ISSUE TITLE
[ADAP-433] [Feature] Granular execution project

### ISSUE THREAD

**Issue by VasiliiSurov** [dbt-labs/dbt-bigquery#647]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

With Google introducing new BigQuery editions we can make dbt run more cost efficient if we could manage execution project on a model like, somewhat how it's implemented in Snowflake adapter.

Some of the models are CPU-bound and will cost less if they are executed using on-demand price model, other could by IO-bound and will cost less if executed on Standard/Enterprise Edition.

This feature should work as a new model configuration that can be set on a project / folder / model level.

### Describe alternatives you've considered

No dbt-native support, only artificially split dbt DAG into slices and use external orchestration with multiple targets

### Who will this benefit?

All users of dbt-bigquery adapter who can invest time into advanced cost management

### Are you interested in contributing this feature?

Yes, if provided some guidence.

**Comment by dbeatty10** [comment]
Thanks for making this feature suggestion [@VasiliiSurov](https://github.com/VasiliiSurov) !

Are you thinking this would be similar to the [`snowflake_warehouse`](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#configuring-virtual-warehouses) model configuration?

I read briefly about [BigQuery editions](https://cloud.google.com/bigquery/docs/editions-intro), but I couldn't determine how to specify the "execution project" differently from the "dataset project" in BigQuery. Do you know how? e.g., can you explain what the API call, Python connection parameters, or SQL session parameters would look like?

**Comment by VasiliiSurov** [comment]
@dbeatty10 
Yes, I would expect this new configuration parameter to be like `snowflake_warehouse` and in BigQuery implementation it will extend `execution_project` from Connection https://github.com/dbt-labs/dbt-bigquery/blob/ea0833424c6445cff853e82ab9a5d563a55d3856/dbt/adapters/bigquery/connections.py#L111 

The way how I saw it we will need more than a single connection, but a connection per `execution_project` that we have in the dbt DAG that is currently running. We can keep total number of threads across all the projects for consistency or per execution project which can make dbt a bit more performant

**Comment by dbeatty10** [comment]
Thanks for connecting the dots for me @VasiliiSurov !

In Snowflake, we can do something like this:
```sql
use warehouse my_purple_tshirt
```

Do you know if we can do something similar in BigQuery?
```sql
SET @@dataset_project_id = 'MyProject';
```

If not, then the comments [here](https://github.com/dbt-labs/dbt-bigquery/issues/343#issuecomment-1320611998) and [here](https://github.com/dbt-labs/dbt-bigquery/issues/343#issuecomment-1325707183) will be especially relevant.

Either way, it sounds like you are asking the similar/same thing as https://github.com/dbt-labs/dbt-bigquery/issues/343 (which itself is similar to https://github.com/databricks/dbt-databricks/issues/59).

**Comment by VasiliiSurov** [comment]
@dbeatty10 

Looks like [this](https://github.com/dbt-labs/dbt-bigquery/issues/343) one is very much a like what I'm asking. As far as I know you can define "compute" project only on a [connection level](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/insert#path-parameters) and once defined it can't be overwritten on a job level.

That's why I was proposing to have a set of connections instead of a single one in current implementation.

**Comment by jtcohen6** [comment]
> That's why I was proposing to have a set of connections instead of a single one in current implementation.

I'd like this, too :) It's going to be a much bigger lift, but something that I'd like to see us building over the medium term.

**Comment by Fleid** [comment]
If BQ's doing it, it feels more like a trend than just Snowflake? So should we consider moving the choice of "compute environment" at the model level across the board, rather than the connection level?

Intuitively, if most platforms would allow the switch to be made in session, like Snowflake with 'USE WAREHOUSE', that would be an easy pull. But for something like BQ, if that means spinning up and down heterogeneous connections as we move through the DAG (or keeping them alive and using them as we go I guess), that sounds much more interesting. 

@jtcohen6 do you think that's a core thing, or a BQ thing? Personally I would start here first, and generalize if that makes sense later. We have enough top down initiatives in flight anyway.

@VasiliiSurov I'm thinking that the next step is to spike it on our side to map the territory. From there, we may use your help, but that could be a complicated one.
