### ISSUE TITLE
[ADAP-492] [Feature] Support partition_by and cluster_by on python models when supplied in model configurations

### ISSUE THREAD

**Issue by kalanyuz** [dbt-labs/dbt-bigquery#680]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This issue was previous raised before in https://github.com/dbt-labs/dbt-bigquery/issues/247 but is now marked as stale and closed.

Currently, Python models do not support table creation with `partition_by` and `cluster_by` when supplied to the model configuration, despite the spark-bigquery-connector having support for it with `indirect` save mode.

I believe we can support for both configurations by modifying `materializations/table.sql` https://github.com/dbt-labs/dbt-bigquery/blob/1972d72b53f897f85188b1218431c6610602bf5c/dbt/include/bigquery/macros/materializations/table.sql#L109
to something like
```python
df.write \
  .mode("overwrite") \
  .format("bigquery") \
  .option("writeMethod", "indirect").option("writeDisposition", 'WRITE_TRUNCATE') \
  {%- if partition_config.data_type | lower in ('date','timestamp','datetime') %}
  .option("partitionField", "{{- partition_config.field -}}") \
  .option("partitonType", "{{- partition_config.granularity -}}") \
  {%- endif %}
  {%- if raw_cluster_by is not none %}
  .option("clusteredFields", "{{- raw_cluster_by|join(',') -}}") \
  {%- endif %}
  .save("{{target_relation}}")
{% endmacro %}
```

### Who will this benefit?

All BigQuery users who are looking to create complex models using dataproc

### Are you interested in contributing this feature?

yes

**Comment by dbeatty10** [comment]
This would be good to have @kalanyuz 🤩 

Would you be interested in opening up a PR with your solution?

**Comment by kalanyuz** [comment]
Definitely. What do I need?On Apr 25, 2023, at 23:35, Doug Beatty ***@***.***> wrote:﻿
This would be good to have @kalanyuz 🤩
Would you be interested in opening up a PR with your solution?

**Comment by kalanyuz** [comment]
@dbeatty10 I've submitted a PR [here](https://github.com/dbt-labs/dbt-bigquery/pull/681)

**Comment by jtcohen6** [comment]
(Much older issue for this: https://github.com/dbt-labs/dbt-bigquery/issues/247)
