### ISSUE TITLE
[ADAP-502] [Regression] 400 PATCH `Policy tags can only be attached to a leaf field.`

### ISSUE THREAD

**Issue by steve-marmalade** [dbt-labs/dbt-bigquery#686]
### Is this a regression in a recent version of dbt-bigquery?

- [X] I believe this is a regression in dbt-bigquery functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

After upgrading to DBT 1.5, several models are failing with the error 400 PATCH `Policy tags can only be attached to a leaf field.` It's not happening to every model, but there's also nothing obvious about them that indicates what the issue is.

### Expected/Previous Behavior

These models ran successfully

### Steps To Reproduce

Unfortunately, I don't have a toy example to reproduce this issue.

### Relevant log output

```shell
16:26:39  Completed with 4 errors and 0 warnings:
16:26:39  
16:26:39  400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/my-project/datasets/my-dataset/tables/my-table?prettyPrint=false: Policy tags can only be attached to a leaf field.
```

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS (via Github Actions)
- Python: 3.10.6
- dbt-core (working version): 1.4.6
- dbt-bigquery (working version): 1.4.0
- dbt-core (regression version): 1.5.0
- dbt-bigquery (regression version): 1.5.0
```

Installed via `pipx install dbt-bigquery --include-deps`

### Additional Context

In my search, this issue seems like it might be related https://github.com/dbt-labs/dbt-bigquery/issues/605

**Comment by dbeatty10** [comment]
Thanks for reporting this @steve-marmalade !

I haven't gotten a chance to dive in yet, but this looks like a similar/same error message as in https://github.com/dbt-labs/dbt-bigquery/issues/687

**Comment by patricker** [comment]
I had the exact same issue. I initially reported in the dbt-core repo, so didn't see yours.
https://github.com/dbt-labs/dbt-bigquery/issues/687

**Comment by dbeatty10** [comment]
I'm going to close this one in favor of https://github.com/dbt-labs/dbt-bigquery/issues/687

If they end up being unique from each other, then we can re-open it.

Thank you both @steve-marmalade and @patricker 🙏

**Comment by steve-marmalade** [comment]
Thanks @patricker and @dbeatty10 🙏
