### ISSUE TITLE
[ADAP-505] [Regression] v1.5 breaks models with descriptions of BigQuery struct columns

### ISSUE THREAD

**Issue by bendiktv2** [dbt-labs/dbt-bigquery#691]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am not able to add descriptions to `STRUCT`-columns in DBT v1.5.

### Expected Behavior

I should be able to add descriptions to `STRUCT`-columns and their nested columns, as I was able to do in versions prior to 1.5.

### Steps To Reproduce

```sql
# models/bugged.sql
{{ config(materialized='table') }}

SELECT
  STRUCT( "complete" AS status ) AS nested
```

```yaml
# models/bugged.yml
version: 2

models:
  - name: bugged
    columns:
      - name: nested
        description: "Describe the nested struct"
```

Run `dbt run --full-refresh --select bugged`

### Relevant log output

```shell
08:35:55  Running with dbt=1.5.0
08:35:56  Unable to do partial parsing because saved manifest not found. Starting full parse.
08:36:01  Found 1 models, 0 tests, 0 snapshots, 0 analyses, 0 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
08:36:01  
08:36:03  Concurrency: 16 threads (target='dev')
08:36:03  
08:36:03  1 of 1 START sql table model my_dataset.bugged ............................ [RUN]
08:36:07  Unhandled error while executing target/run/my_model/models/bugged.sql
400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/my-project/datasets/my_dataset/tables/bugged?prettyPrint=false: Policy tags can only be attached to a leaf field.
08:36:07  1 of 1 ERROR creating sql table model my_dataset.bugged ................... [ERROR in 3.55s]
08:36:07  
08:36:07  Finished running 1 table model in 0 hours 0 minutes and 5.80 seconds (5.80s).
08:36:07  
08:36:07  Completed with 1 error and 0 warnings:
08:36:07  
08:36:07  400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/my-project/datasets/my_dataset/tables/bugged?prettyPrint=false: Policy tags can only be attached to a leaf field.
08:36:07  
08:36:07  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: MacOS Ventura 13.3.1 (22E261)
- Python: Python 3.11.3
- dbt:

Core:
  - installed: 1.5.0
  - latest:    1.5.0 - Up to date!

Plugins:
  - bigquery: 1.5.0 - Up to date!
```

### Additional Context

Probably related to https://github.com/dbt-labs/dbt-bigquery/issues/673, but that is a feature request for data_type and contract enforcment, this bug-issue is a breaking change.

**Comment by bendiktv2** [comment]
Markdown removed the link to the possibly related issue, so adding it here for links: https://github.com/dbt-labs/dbt-bigquery/issues/673

**Comment by bendiktv2** [comment]
It appears this config is also required to reproduce the error:
```yaml
# dbt_project.yml
models:
    my_model:
      +persist_docs:
        columns: true
```

**Comment by StoryFabian** [comment]
Just found out we have the same issue.
This is a huge breaking change as we have a lot of nested columns documented.

**Comment by StoryFabian** [comment]
#687 

This one is related

**Comment by dbeatty10** [comment]
Thanks for reaching out @bendiktv2 and @StoryFabian !

This is the same as https://github.com/dbt-labs/dbt-bigquery/issues/687, so I'm going to close this in favor of that one.

There is a PR to fix this that you can track along with: https://github.com/dbt-labs/dbt-bigquery/pull/688
