### ISSUE TITLE
[ADAP-515] [Regression] persist_docs on column type RECORD causes HTTP 400 Bad Request: Policy tags can only be attached to a leaf field

### ISSUE THREAD

**Issue by emilmar** [dbt-labs/dbt-bigquery#699]
### Is this a regression in a recent version of dbt-bigquery?

- [X] I believe this is a regression in dbt-bigquery functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

When applying description to a `RECORD` column with persist_docs, the table/view gets created in BigQuery but fails to be updated with the documentation. The dbt invocation gets an unhandled error and completes with an error.

`400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/<project_id>/datasets/<dataset_id>/tables/<table_id>?prettyPrint=false: Policy tags can only be attached to a leaf field.`

No policy tags are defined the `model.yml` but the error message still claims it is a policy tag issue.
**Note:** This is about documentation on the record itself, not on any of its struct properties.

### Expected/Previous Behavior

I expect the documentation to be added on the `RECORD` column in BigQuery.
Previous behavior was that it was not added at all, but the code still ran.

### Steps To Reproduce

Create a table/view that contains a column of type `RECORD`

```
CREATE TABLE dbt_bigquery_issues.record_documentation_bug (
  my_record_col RECORD
    <field1 STRING,
     field2 STRING>
);
```
Create a view on top of this table, remember to persist_docs. `record_documentation_bug_view.sql`

```
{{ config(
  persist_docs={"relation": true, "columns": true}
) }}

select
*
from `project_id.dbt_bigquery_issues.record_documentation_bug`

```

and add documentation to the `model.yml`

```
version: 2
models:
  - name: record_documentation_bug_view
    columns:
      - name: my_record_col
        description: test
```

Run the model.

### Environment

```markdown
- OS: Windows 10 (and Ubuntu 22.04 tested)
- Python: 3.11.2
- dbt-core (working version): 1.4.1.
- dbt-bigquery (working version): 1.4.1
- dbt-core (regression version): 1.5.0
- dbt-bigquery (regression version): 1.5.0
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @emilmar !

I think this is the same as https://github.com/dbt-labs/dbt-bigquery/issues/687 (which will have a fix shipped in our next patch release).

I'm going to close this as a duplicate, but let me know if this looks unique and we can re-open it.

**Comment by emilmar** [comment]
Hi @dbeatty10, thank you for the quick triage. You're correct, it is the same. I did my best to search for the issue but to no avail.
Thanks for making a great product.

**Comment by dbeatty10** [comment]
You're welcome @emilmar ❤️

Thank **you** for noticing this and taking the time to report it and make sure it didn't slip through the cracks -- much appreciated! 🏆
