### ISSUE TITLE
[Feature] Align dbt-bigquery with dbt-core third party dependencies 

### ISSUE THREAD

**Issue by Dizzyobeah** [dbt-labs/dbt-bigquery#709]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Hi,

Latest versions of Google Cloud Composer comes with agate 1.7.0 preinstalled.
This prevents us from installing dbt-bigquery since the requirement is agate 1.6.3.
If possible please align agate version with that of dbt-core (1.6.3-1.7.0).

### Describe alternatives you've considered

Use an earlier version of Google Cloud Composer where agate 1.6.3 is installed as trying to resolve all other dependencies in a pre-built solution is not to recommend.

### Who will this benefit?

Everyone using Google Cloud Composer and need to run later versions.

### Anything else?

https://cloud.google.com/composer/docs/concepts/versioning/composer-versions

**Comment by dbeatty10** [comment]
Thanks for reporting this @Dizzyobeah !

dbt-bigquery got its own `agate` dependency added in https://github.com/dbt-labs/dbt-bigquery/pull/458, but I'm not sure why.

We could try deleting this line and see if it passes CI:
https://github.com/dbt-labs/dbt-bigquery/blob/f717e83927e5ac71c4a085985ecc95e7c0c70099/setup.py#L81
