### ISSUE TITLE
[ADAP-551] [Bug] Datetime incremental tables scanning more of table than expected

### ISSUE THREAD

**Issue by pcreux** [dbt-labs/dbt-bigquery#717]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a table partitioned by day on a datetime column. When running an incremental run BigQuery performs a full table scan instead of an optimized partition scan.

This is likely due to a BigQuery bug where the function `datetime_trunc` ignores partitions. 

Example:

```sql
-- `events` is partitioned by day on the datetime column `created_at`
select * from events where datetime_trunc(created_at, DAY) in (current_date) -- 650GB
select * from events where timestamp_trunc(created_at, DAY) in (current_date) -- 100MB
select * from events where date(created_at) in (current_date) -- 100MB
```

### Expected Behavior

Optimized partition scan with 100mb usage but I'm seeing a full table scan with 650gb usage.

### Steps To Reproduce

The `events` table is partitioned by day on a datetime column with the following config:

```
{{ config(
    materialized='incremental',
    unique_key='id',
    partition_by={
      "field": "created_at",
      "data_type": "datetime"
    },
    incremental_strategy = 'insert_overwrite',
    partitions = [ 'current_date', 'date_sub(current_date, interval 1 day)' ]
  )
}}
```

Running an incremental sync will use `datetime_trunc` resulting in a full table scan. Here is an extract from the `run` code:

```sql
    merge into `zipline-datawarehouse`.`analytics`.`events` as DBT_INTERNAL_DEST
        using (
  --- SQL MODEL CODE
) as DBT_INTERNAL_SOURCE
        on FALSE
    when not matched by source
         and datetime_trunc(DBT_INTERNAL_DEST.created_at, day) in (
              current_date, date_sub(current_date, interval 1 day)
          )
        then delete
    when not matched then insert
        (COLUMNS)
    values
        (COLUMNS)
```

### Environment

```markdown
- OS: MacOS
- Python: 3.10.9
- dbt-core: 1.5.0
- dbt-bigquery: 1.5.0
```

### Additional Context

We can work around this issue by setting the `partition_by.data_type` to `timestamp`. `dbt` will happily use `timestamp_trunc` and BigQuery will only look up the necessary partitions. (Note that this was working in v1.2, it stopped working in v1.4, and it's now working again in v 1.5).

```
{{ config(
    materialized='incremental',
    unique_key='id',
    partition_by={
      "field": "created_at",
      "data_type": "timestamp"
    },
    incremental_strategy = 'insert_overwrite',
    partitions = [ 'current_date', 'date_sub(current_date, interval 1 day)' ]
  )
}}
```

A similar issue with `date` partitioning but it doesn't seem to be the same cause: https://github.com/dbt-labs/dbt-bigquery/issues/708

A mention of the bug where `datetime_trunc` makes BigQuery perform full table scans: https://github.com/dbt-labs/dbt-utils/issues/393

**Comment by dbeatty10** [comment]
Thanks for reaching out @pcreux !

I'm not a seeing a difference between the config you reported in the "Steps To Reproduce" vs. the workout in the "Additional Context" section.

Is it as simple as this, or is there more involved?
```diff
- "data_type": "datetime"
+ "data_type": "timestamp"
```

Could you take a peek and update as needed?

**Comment by pcreux** [comment]
Hey @dbeatty10 ! You are right, it's indeed `"data_type": "timestamp"`.  I just updated the code snippet.

**Comment by dbeatty10** [comment]
> This is likely due to a BigQuery bug where the function `datetime_trunc` ignores partitions.

@pcreux do you have a link to this bug report on the Google side of things? It will be good to hear what Google says about it.

If their guidance is to just use `timestamp_trunc` instead of `datetime_trunc` when the underlying data type of the partitioned column is `datetime`, then the fix would fairly simple here:
https://github.com/dbt-labs/dbt-bigquery/blob/495566a24e9e8a1f35ee366ae1ecf8e944a6f966/dbt/adapters/bigquery/impl.py#L123-L126

Probably something like:
```python
        if self.data_type_should_be_truncated() and self.data_type == "datetime":
            return f"timestamp_trunc({column}, {self.granularity})"
        elif self.data_type_should_be_truncated():
            return f"{self.data_type}_trunc({column}, {self.granularity})"
        else:
            return column
```

**Comment by github-christophe-oudar** [comment]
I had a few changes to solve issues with trunc functions in https://github.com/dbt-labs/dbt-bigquery/commit/7c216445f8009baa9cec4d61dd56693be1dd79fa
Could you try 1.6.X version to see if it works better for you?
