### ISSUE TITLE
[ADAP-552] [Bug] - incremental strategy issues when cmek required

### ISSUE THREAD

**Issue by gregorio-vettori-sdg** [dbt-labs/dbt-bigquery#718]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

![dbt cmek log error](https://github.com/dbt-labs/dbt-bigquery/assets/109951033/ca67e57f-a7b9-4f0d-8bc6-f8f1dca42336)

Hi everyone, my team and I are experiencing an issue when trying to execute merge statements (incremental_strategy = 'insert_overwrite') when using dbt with bigquery. While dbt is able to perform classic merge, dbt is not able to perform a delete insert by partition when the cmek is required on bigquery. 
The cmek was defined in the dbt_project.yml but this doesn't seem to solve the issue.

### Expected Behavior

We would expect dbt would be able to perform merge loading on the tables already created.

### Steps To Reproduce

1. A BigQuery project where CMEK is required
2. A model performing a merge statement on a pre-existing table

### Environment

```markdown
- OS:
- Python: 3.9.13
- dbt-core: 
- dbt-bigquery: 1.5.0
```

**Comment by dbeatty10** [comment]
Thanks for reaching out @gregorio-vettori-sdg !

Are you saying that neither of the following options for configuring [`kms_key_name`](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#using-kms-encryption) worked for you?

Note: Both options below assume that you replace the dummy values for `kms_key_name` below with your actual [key_resource_id](https://cloud.google.com/bigquery/docs/customer-managed-encryption#key_resource_id).

### Option 1: model-level config

`models/my_incremental_model.sql`
```sql
{{ config(
    materialized="incremental",
    incremental_strategy="insert_overwrite",
    kms_key_name="projects/PROJECT_ID/locations/global/keyRings/test/cryptoKeys/quickstart",
    ...
    }
) }}
```

### Option 2: project-level config

`dbt_project.yml`
```yml

name: my_project
version: 1.0.0

...

models:
  my_project:
    encrypted:
      +kms_key_name: 'projects/PROJECT_ID/locations/global/keyRings/test/cryptoKeys/quickstart'
```

**Comment by gregorio-vettori-sdg** [comment]
Hi @dbeatty10 ,

Honestly we have just tried option 2 (the project-level config), assuming option 1 would not have led to better results. By the way, we may have found a solution by  setting the known encryption key as the default one at project level on Google Bigquery. This seems to work, but surely, we need to perform more testing.

**Comment by dbeatty10** [comment]
@gregorio-vettori-sdg nice to hear that setting the known encryption key as the default one at the project level within Google BigQuery might work for you.

I'd still be interested to hear the result if if you are willing to see if Option 1 (model-level config) is causing problems for you too, or if you're only experiencing problems with Option 2 (project-level config).
