### ISSUE TITLE
partition_by did not create table with corresponding fields

### ISSUE THREAD

**Issue by minhnhat992** [dbt-labs/dbt-bigquery#72]
### Describe the bug
I was trying to create a bigquery table with a specified partition field and 'day' granularity. However, running the with the below config only generate a table with the pseudo-column _PARTITIONTIME.

In similar fashion, declared cluster_key does not show up in the final table

```
{{ config(
    materialized = 'table',
    partition_by={
      "field": "partition_date",
      "data_type": "date",
      "granularity": "day"
    },
    cluster_by=["partition_date"],
    partitions=dbt.partition_range(var('dates', default=yesterday())),
    verbose=True
)}}
```

### Steps To Reproduce
- run the following command to generate the data set
`dbt --full-refresh -m page_view_2 --vars 'dates: "20210701, 20210703"'`
### Expected behavior
```
Running with dbt=0.20.2

Found 6 models, 0 tests, 0 snapshots, 0 analyses, 165 macros, 0 operations, 0 seed files, 2 sources, 0 exposures

16:39:11 | Concurrency: 1 threads (target='dev')
16:39:11 | 
16:39:11 | 1 of 1 START table model wc_data_core_MB_DEV.page_view_2............. [RUN]
16:39:12 | -> Running for day 20210701
16:39:21 | -> Running for day 20210702
16:39:30 | -> Running for day 20210703
16:39:36 | 1 of 1 OK created table model wc_data_core_MB_DEV.page_view_2........ [CREATED 3 PARTITIONS in 24.92s]
16:39:36 | 
16:39:36 | Finished running 1 table model in 26.05s.
```

### System information
**The output of `dbt --version`:**

```
installed version: 0.20.2

Plugins:
  - snowflake: 0.20.2
  - postgres: 0.20.2
  - bigquery: 0.20.2
  - redshift: 0.20.2
  - snowflake: 0.20.2
  - postgres: 0.20.2
  - bigquery: 0.20.2
  - redshift: 0.20.2
```

**The operating system you're using:** Mac OS Monterey

**The output of `python --version`:**
Python 3.6.15

**Comment by minhnhat992** [comment]
For more context, I was going along with the tutorial for BQ date_sharded_table function [link](https://docs.getdbt.com/docs/guides/database-specific-guides/creating-date-partitioned-tables)

**Comment by minhnhat992** [comment]
so after spending a bit of time on it, it seems the date_sharded_table function is the main reason for this issue, not sure why but I got the correct partition field created if I stopped using this function

**Comment by jtcohen6** [comment]
@minhnhat992 The capability to create date-sharded tables was added a _long_ time ago, before the introduction of column-based partitioning and clustering (`partition_by` + `cluster_by`). That functionality been effectively unmaintained for several years now, so we decided to officially deprecate + remove it in dbt-bigquery v1.0.0 (#20, #42).

The tutorial you've linked above has been unlisted for a while, and it will be officially deprecated in v1: https://next.docs.getdbt.com/docs/guides/database-specific-guides/creating-date-partitioned-tables

In the meantime, you can continue to use `partition_by` + `cluster_by` with table models, and the `partitions` config with incremental models using the "static" `insert_overwrite` strategy: https://docs.getdbt.com/reference/resource-configs/bigquery-configs#the-insert_overwrite-strategy.

I'd be interested in re-adding native support for models comprised of multiple partitions / "shards," conceptually similar to date-partitioned tables in BigQuery, but (as with all things dbt) preferably managed via SQL/DDL/DML. You can check out a long-lived issue that discusses this proposal in depth: https://github.com/dbt-labs/dbt-core/issues/1637
