### ISSUE TITLE
[ADAP-600] [Feature] Automated release of dbt-bigquery image (package)

### ISSUE THREAD

**Issue by christopherekfeldt** [dbt-labs/dbt-bigquery#751]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When a new release is set as LTS in this repo, then it would be neat if a automated update of the dbt-bigquery image is updated at the same time. 

### Describe alternatives you've considered

Create a Github workflow that once a new release is set also updated the existing dbt-package with a new docker image reflecting the new version. 

### Who will this benefit?

All users who want to leverage the new dbt-bigquery release that also uses your package(image).

At my company for example we use Google Cloud Workflows. Many of our different workflows holds different steps solving different tasks, one of them is using your dbt-bigquery image to solve transformations with dbt. We use other images like hashicorps for solving terraform stuff. 

By doing so we don't have to maintain our own images. Which is awesome! 

### Are you interested in contributing this feature?

No

### Anything else?

Here is a link to another dbt-package which does exact this, pushing their new image up to container registry once they do a new release.

https://github.com/elementary-data/elementary/blob/master/.github/workflows/release.yml

**Comment by khaledh** [comment]
Sorry to resurrect this issue, but it'd be great if the `dbt-bigquery` docker image gets released automatically with new releases (similar to `dbt-core`).
