### ISSUE TITLE
[ADAP-659] [CT-2745] [Bug] BigQuery merge fails when partition is required

### ISSUE THREAD

**Issue by Strimboli** [dbt-labs/dbt-bigquery#792]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Trying to migrate a BQ stored procedure to DBT where the partition on the target table is required. I receive this error on the table the requires a partition:

> BadRequest("
>     Cannot query over table 'test' without a filter over column(s) 'date' that can be used for partition elimination")

### Expected Behavior

I would expect the ability to manage a table in such a way similar to how we mange `insert_overwrite` partitioning where I can provide a list of dates say, last 14 days, and have the target filtered and merge on that look back period. 
I cannot use `insert_overwrite` at the moment because I am not merging from the whole set of data, so I would lose data that has not been updated when the merge should take care of not losing an unmatched ID. 

### Steps To Reproduce

Build this twice to reproduce, second will be failure. I have tried on `1.4` and `1.5` to no avail.

```sql
{{
    config(
        materialized="incremental",
        incremental_strategy="merge",
        partition_by={
            "field": "date",
            "data_type": "DATE",
            "granularity": "day",
        },
        unique_key="value",
        require_partition_filter=true,
    )
}}

select
    current_date() as date,
     1 as value
```

### Environment

```markdown
- dbt-cloud: 1.4
```

### Which database adapter are you using with dbt?

bigquery

**Comment by github-christophe-oudar** [comment]
I ran into that issue too in the past and it's not obvious how to deal with that condition in the MERGE statement.
It could be something like adding a way to define a "hack" to add a "dumb" condition like `date > "1970-01-01"` for date.

A hacky workaround could be to have prehook that runs:
```
ALTER TABLE dataset.table
SET OPTIONS(
    require_partition_filter = false
)
```
(and same one with true in post hook)

**Comment by dataders** [comment]
> I did find this [GCP forum post](https://www.googlecloudcommunity.com/gc/Data-Analytics/Bigquery-Error-when-using-partition-filter-and-false-condition/m-p/609514) from less than two months ago. I'm not 100% that it is the same error, but it smells the fame. here's an excerpt:
> 
> > The error message you're encountering is due to an issue with BigQuery's optimizer. It's incorrectly removing the filter on the `tstamp` column, assuming the false condition will always be false. As a result, it scans all partitions in the `'test_partitioned_table'` table, even though the `tstamp` filter should limit it to the `'2023-03-01'` partition only.
> > This is a known bug in BigQuery's optimizer. Google has been notified about this issue and they're currently working on a solution.

I got a [fast, helpful response from the BQ wizard](https://www.googlecloudcommunity.com/gc/Data-Analytics/Bigquery-Error-when-using-partition-filter-and-false-condition/m-p/628020#M2733) confirming that this is a BQ optimizer bug
