### ISSUE TITLE
[ADAP-691] [Feature] add incremental strategy append

### ISSUE THREAD

**Issue by leo-schick** [dbt-labs/dbt-bigquery#811]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Other dbt adapters support the incremental stragey `append` but dbt-bigquery does not: [Supported incremental strategies by adapter](https://docs.getdbt.com/docs/build/incremental-models#supported-incremental-strategies-by-adapter)

I was wondering why this has not been implemented since it is quite useful when you want to create a log table holding snapshot data with a timestamp.
I found blog item [Creating “Append” Materialization in dbt (data build tool)](https://medium.com/tiket-com/creating-append-materialization-in-dbt-1469c8beafc3) which discusses addinng `append_only` as a materialization option to dbt-bigquery on an older dbt version, so it must be possible to do that in big query.

### Describe alternatives you've considered

I implemented this now with `merge` by using a column with `current_timestamp()` as key. That works not perfect:
* when running full_refresh, the data gets lost
* it is a total overhead creating unnecessary processing time

### Who will this benefit?

People building historical data tables or people which use the incremental strategy `append` with another adapeter and now want to switch their dbt project over to big query.

**Comment by rloredo** [comment]
If you do merge without a unique key specification the behaviour should be append only.
This is in the [documentation](https://docs.getdbt.com/docs/build/incremental-models#defining-a-unique-key-optional)

`Not specifying a unique_key will result in append-only behavior, which means dbt inserts all rows returned by the model's SQL into the preexisting target table without regard for whether the rows represent duplicates.
`

But I haven't tested it.

**Comment by leo-schick** [comment]
@rloredo OK, nice to know. I think this should be implemented by default so that this works equal to the other db provider with incremental strategy `append`.

**Comment by dbeatty10** [comment]
Thanks for raising this @leo-schick !

I think this would be covered by the work in https://github.com/dbt-labs/dbt-core/issues/9290. Namely, these two:
- https://github.com/dbt-labs/dbt-bigquery/issues/242
- https://github.com/dbt-labs/dbt-bigquery/issues/523

So I'm going to leave this closed as a duplicate of those ones.
