### ISSUE TITLE
[ADAP-697] [Feature] Test complete matrix of incremental strategy configuration

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-bigquery#824]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Our current testing strategy for the many approaches to incremental sql for bigquery is, at best, haphazard. We need to test the complete matrix of parameters so that we can properly protect against regressions and make changes to this with confidence. See #630 or the many other examples of edge cases we have run into reactively. 

Current Tests: https://github.com/dbt-labs/dbt-bigquery/blob/main/tests/functional/adapter/incremental/test_incremental_strategies.py

Instead of using singular fixtures we should instead have a function which generates n models where n is the product of all incremental configuration parameters.

**Comment by dataders** [comment]
@colin-rogers-dbt perhaps this should be a core issue?

**Comment by colin-rogers-dbt** [comment]
@dataders the test fixtures here will be very adapter specific and this is a particularly acute problem in dbt-bigquery
