### ISSUE TITLE
[ADAP-757] SyntaxError: walrus operator in Python 3.7

### ISSUE THREAD

**Issue by cemsbr** [dbt-labs/dbt-bigquery#849]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

SyntaxError in Python 3.7 with version >=1.5.4 due to [walrus operator](https://github.com/dbt-labs/dbt-bigquery/blob/2bce97721fb7f7733e0a49ec97430072720d7033/dbt/adapters/bigquery/column.py#L230).

### Expected Behavior

No SyntaxError or unable to install these versions with Python 3.7

### Steps To Reproduce

```bash
python3.7 -m venv /tmp/dbt-venv
source /tmp/dbt-venv/bin/activate
pip install dbt-bigquery
python -c "from dbt.adapters.bigquery.column import BigQueryColumn"
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/dbt-venv/lib/python3.7/site-packages/dbt/adapters/bigquery/__init__.py", line 4, in <module>
    from dbt.adapters.bigquery.column import BigQueryColumn  # noqa
  File "/tmp/dbt-venv/lib/python3.7/site-packages/dbt/adapters/bigquery/column.py", line 230
    if existing_nested_column_data_type := nested_column_data_types.get(root_column_name):
                                         ^
SyntaxError: invalid syntax
```

### Environment

```markdown
- OS: Lubuntu 22.04
- Python: 3.7
- dbt-core: 1.5.4
- dbt-bigquery: 1.5.4
```

### Additional Context

I believe this line line should be updated: https://github.com/dbt-labs/dbt-bigquery/blob/2bce97721fb7f7733e0a49ec97430072720d7033/setup.py#L94

**Comment by dbeatty10** [comment]
Thanks for reaching out @cemsbr !

Agreed that we should make this simple update (like in [dbt-postgres](https://github.com/dbt-labs/dbt-core/blob/991618dfc152e3316d4900a29c3bc8b44c818664/plugins/postgres/setup.py#L89), [dbt-redshift](https://github.com/dbt-labs/dbt-redshift/blob/6f31211a1fc84a346ba6588072fcb0de8dc890fa/setup.py#L106), [dbt-spark](https://github.com/dbt-labs/dbt-spark/blob/4ce348a24d341976c094acc2c4e5123082eed49d/setup.py#L97), and [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/22f50a9d66c8ecb921c8a32cc5c5c8372dc42d2f/setup.py#L88)):
```python
    python_requires=">=3.8",
```

**Comment by cemsbr** [comment]
If you'd like to keep 1.5.* compatible with python 3.7, there is more work to do before releasing the next 1.5 patch version. Maybe some dependent projects using Python 3.7 pinned 1.5.*.

**Comment by dbeatty10** [comment]
> If you'd like to keep 1.5.* compatible with python 3.7, there is more work to do before releasing the next 1.5 patch version. Maybe some dependent projects using Python 3.7 pinned 1.5.*.

In #742, we dropped support for 3.7 for both 1.4.* and 1.5.*, since it reached end of life on [2023-06-27](https://devguide.python.org/versions/).
