### ISSUE TITLE
Cannot Access CSV on Google Drive when using OAuth

### ISSUE THREAD

**Issue by gio-sourcing-auto** [dbt-labs/dbt-bigquery#85]
### Describe the bug

When using the OAuth method to do a federated query for a table that points to a CSV file on Drive, I get an error.

When using a service account to access the same file, it works just fine.

• I have full permissions to the file
• All GDrive APIs in Google Cloud and Google Workspace are turned on
• I've also run the following command

```
gcloud auth application-default login \
  --scopes=https://www.googleapis.com/auth/bigquery,\
                    https://www.googleapis.com/auth/drive.readonly,\ 
                    https://www.googleapis.com/auth/iam.test
```
• I've also tried revoking auth and re-authing

### Steps To Reproduce
• Place a (CSV) file in a drive and share it with yourself
• Make a table in Bigquery that uses the Drive file as the source (federated)
• SELECT * the table via dbt

### Expected behavior
I expect it to be able to query the table.

### Screenshots and log output
```
Access Denied: BigQuery BigQuery: Access Not Configured. Drive API has not been used in project 764086051850 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/drive.googleapis.com/overview?project=764086051850 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
  compiled SQL at ...
```

What's weird is that the project ID is not one of ours. When using a service account, the correct project is used. My profile.yml is set up correctly, so I don't know where this project ID is coming from.

I've noticed this issue happening with a similar project ID [on StackOverflow](https://stackoverflow.com/questions/48672690/querying-federated-tables-google-drive-via-bigquery-python-api)

### System information
**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.21.0
  - snowflake: 0.21.0
  - redshift: 0.21.0
  - postgres: 0.21.0
```

**The operating system you're using:**
Mac OS Big Sur version 11.6
Python 3.8.5

**Comment by McKnight-42** [comment]
Thanks @gio-sourcing-auto so much for bringing this to our attention.

After trying to replicate your issue we were able to set up a federated query for both oauth and service account methods. a few ideas as to why your setup might not be working are:

1. the local sdk for gcloud is pointing to wrong project
 can use `gcloud config get-value project`  to make sure project is what you expect locally. if this is not what you expect you can run `gcloud config set project <projectname> ` to change projects.
2. there are some permissions issues between the bigquery account or project and the local gcloud.

if neither of these options help please let me know and we can keep debugging this together.

**Comment by balmasi** [comment]
Hi @McKnight-42 This problem still seems to be occurring. Not sure why you weren't able to reproduce. Maybe it needs to be a shared drive?

A little web investigation brought up a [newer blog post](https://medium.com/google-cloud/google-oauth-credential-going-deeper-the-hard-way-f403cf3edf9d) that points to the issue.

Once you use `gcloud auth application-default login` and authorize using OAuth, you will notice that the credentials saved in the default location `~/.config/gcloud/application_default_credentials.json` do in fact indicate that it points to a project with id: `764086051850`

```json
{
  "client_id": "764086051850-6qr4p6gpi6hn506pt8ejuq83di341hur.apps.googleusercontent.com",
  "client_secret": "<redacted>",
  "quota_project_id": "my-work-project",
  "refresh_token": "<some_refresh_token>",
  "type": "authorized_user"
}
```
This project ID is in fact associated with the **gcloud CLI** as a part of the client that kicks off the OAuth flow.

Of course, this means that there's no way to activate the Drive API on a Google internal project...

Following the instructions in the blog post, I generated new credentials and passed them into the `gcloud auth application-default login` via the `--cliend-id-file` flag and it worked like a charm.

I wonder if this can be automated/baked into the dbt default behaviour.
