### ISSUE TITLE
[CT-1936] Support Google Cloud Auth from AWS Credentials File

### ISSUE THREAD

**Issue by siephen** [dbt-labs/dbt-bigquery#86]
### Describe the feature
Support connecting to BigQuery via from an AWS Credentials File.

### Describe alternatives you've considered
None

### Additional context
[Google Cloud Auth  AWS Docs](https://googleapis.dev/python/google-auth/latest/reference/google.auth.aws.html)

This is how my org does gcloud auth, so we don’t have many alternatives here

### Who will this benefit?
Any user/company who runs Google cloud workloads from AWS and keeps credentials in AWS.

### Are you interested in contributing this feature?
Yes

**Comment by McKnight-42** [comment]
@siephen going to open this issue up and would be more than happy to help in anyway i can.

**Comment by siephen** [comment]
@McKnight-42,

I'm thinking this would manifest as a new method that can be used called `aws` and it would use the following syntax to generate the credentials for the BigQuery Client from the AWS From File method.

Updating the following [IF Block](https://github.com/dbt-labs/dbt-bigquery/blob/072050eb5f5c7d6e464c0b4ae26c3745af505690/dbt/adapters/bigquery/connections.py#L257)


Adding in the type [here](https://github.com/dbt-labs/dbt-bigquery/blob/072050eb5f5c7d6e464c0b4ae26c3745af505690/dbt/adapters/bigquery/connections.py#L76)

Is this the right track?

**Comment by siephen** [comment]
> @McKnight-42,
> 
> 
> 
> I'm thinking this would manifest as a new method that can be used called `aws` and it would use the following syntax to generate the credentials for the BigQuery Client from the AWS From File method.
> 
> 
> 
> Updating the following [IF Block](https://github.com/dbt-labs/dbt-bigquery/blob/072050eb5f5c7d6e464c0b4ae26c3745af505690/dbt/adapters/bigquery/connections.py#L257)
> 
> 
> 
> 
> 
> Adding in the type [here](https://github.com/dbt-labs/dbt-bigquery/blob/072050eb5f5c7d6e464c0b4ae26c3745af505690/dbt/adapters/bigquery/connections.py#L76)
> 
> 
> 
> Is this the right track?
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

@McKnight-42 Bumping my comment.

**Comment by McKnight-42** [comment]
@siephen yes these the above are both spots you will need to add in some logic, may also need to add some new credentials specifically for aws connection here https://github.com/dbt-labs/dbt-bigquery/blob/072050eb5f5c7d6e464c0b4ae26c3745af505690/dbt/adapters/bigquery/connections.py#L89 

would love to see a draft pr on trying to get this to work and keep helping you build it out, already looking into what we might need to add it to CI/CD testing as well on our end.

**Comment by siephen** [comment]
@McKnight-42 , I drafted a PR for this here. I'm working through validating it on local with my internal team. Any initial thoughts? Also, where are the docs that will need to be updated for this new connection method option?

**Comment by McKnight-42** [comment]
@siephen fantastic! i'll pop over to the PR and leave some comments there when I can. as for docs updating i'd say this page https://docs.getdbt.com/reference/warehouse-profiles/bigquery-profile.

If you can I would appreciate any relevant information on what it takes to setup and get running locally yet? so we can test on our end as well to best assist?

**Comment by siephen** [comment]
@McKnight-42 , I have some questions over on the linked PR for this around how to write the test cases, can you take a look when you get a chance?
