### ISSUE TITLE
[ADAP-775] [Feature] Support table constraints

### ISSUE THREAD

**Issue by lilichenghero** [dbt-labs/dbt-bigquery#865]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Bigquery starts supporting primary key set up, which is super helpful for bigquery users with table designs. 

https://cloud.google.com/bigquery/docs/information-schema-table-constraints

dbt-bigquery however does not have the feature embedded according to the documentation. 
https://docs.getdbt.com/terms/primary-key#google-bigquery
Possible to develop this feature? It certainly benefits bigquer + dbt users. 

### Who will this benefit?

All GCP bigquery + dbt users. 

### Are you interested in contributing this feature?

Sure, if I could help.

**Comment by dbeatty10** [comment]
@lilichenghero I'm going to close this as already covered, but just ping us if you think we should consider re-opening it.

**Comment by dbeatty10** [comment]
Thanks for reaching out @bnaul ! Opened https://github.com/dbt-labs/docs.getdbt.com/pull/4419 to get all the docs and source code in alignment with each other.
