### ISSUE TITLE
[ADAP-781] [Feature] Add an option to use INFORMATION_SCHEMA for partition info retrieval

### ISSUE THREAD

**Issue by github-christophe-oudar** [dbt-labs/dbt-bigquery#867]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

So far there are few places where dbt-bigquery access partitions information:
- In incremental materialization, `_dbt_max_partition` is declared (when used in a model) and stores the max partition
- In `get_partitions_metadata` macro that returns the partitions information for input model
- In incremental `insert_overwrite` materialization and before the MERGE statement with dynamic partitions to store them in `dbt_partitions_for_replacement` and use it in the predicate
- In incremental `insert_overwrite` materialization and before the copy partitions statement with dynamic partitions to iterate on the partitions to replace

Allowing to use `INFORMATION_SCHEMA` data would reduce the amount of data scanned.
More details are available on https://cloud.google.com/bigquery/docs/information-schema-partitions.

As this table is still in Preview, it's likely safer to provide as an alternative to current method.

To access that new method, adding `partition_information` settings to `partition_by` config block so that without value the default is current behavior or with explicit value "model" or use information schema with value "information_schema" to use the new approach.

This issue is similar to https://github.com/dbt-labs/dbt-bigquery/issues/286 but intend to rely on existing macros and solutions as well replacing under the hood accesses to improve overall performances.

### Describe alternatives you've considered

We could try to set the config at connection level (profiles.yml) but doing so would change the API for existing macros and wouldn't be as convenient as accessing model config block.

### Who will this benefit?

Anyone using incremental strategy with fairly large partitions as the current approach can be costly and and slightly slow compared to the metadata approach.

### Are you interested in contributing this feature?

yes

**Comment by github-christophe-oudar** [comment]
I just though about one usecase where it doesn't exactly work the same way: if you do `MAX(my_partition_timestamp)`. Then with `INFORMATION_SCHEMA`, it would be truncated to HOUR or DAY since it's the `partition_id` that we would use.
Having an hybrid mode where we would have the the partition id retrieved and then filtered on the actual `MAX(my_partition_timestamp)`. I tested it manually and it's much more efficient.

**Comment by dataders** [comment]
implementing #914 surfaced that some partition info is not available in the INFO SCHEMA, namely the partitions associated with a materialized view [Internal Slack thread](https://dbt-labs.slack.com/archives/C034EV1RH4Z/p1696526644206879).

@wazi55 provided a workaround using the python client, but tacking onto this issue that it should be there.

**Comment by github-christophe-oudar** [comment]
Moving to python instead of SQL for that case appears to be adding quite a lot of complexity in my opinion.
Is it a blocker that materialized views are not fully supported? The implementation I'm offering is allowing to use the current strategy ("model") and we might discuss with Google team to support MV in `INFORMATION_SCHEMA`.

**Comment by wazi55** [comment]
You should be able to use a python model https://docs.getdbt.com/docs/build/python-models and reference the model as a part of your dbt model. There is a ticket raised internally at Google, but like anything, it will take a few weeks to get implemented.

**Comment by amychen1776** [comment]
I'm closing this for now due to a project we have picking up to be announced soon that should make this a more delightful experience.
