### ISSUE TITLE
dbt seed fails on capital letters in dataset names

### ISSUE THREAD

**Issue by caoilte** [dbt-labs/dbt-bigquery#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run `dbt seed` with a dataset name that includes capital letters it fails eg if using "Bananas" instead of "bananas"

### Expected Behavior

That it would work fine.

### Relevant log output

```shell
10:45:53 | Concurrency: 1 threads (target='caoilte')
10:45:53 | 
10:45:53 | 1 of 1 START seed file caoilte_Bananas_raw.seed_top1300 [RUN]
Unhandled error while executing seed.fruit.seed_top1300
404 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/banana-project/jobs?uploadType=resumable: Not found: Dataset banana-project:caoilte_Bananas_raw
10:45:53 | 1 of 1 ERROR loading seed file caoilte_Bananas_raw.seed_top1300 [ERROR in 0.27s]
10:45:53 | 
10:45:53 | Finished running 1 seed in 5.72s.

Completed with 1 error and 0 warnings:

404 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/banana-project/jobs?uploadType=resumable: Not found: Dataset banana-project:caoilte_Bananas_raw
```
```


### Environment

```markdown
- OS: Linux
- Python: 3.8.6
- dbt: 0.21.0
```

### What database are you using dbt with?

bigquery

### Additional Context

dbt/bigquery works fine for capitalised model names (It was trying to make the seed name consistent with the capitalised model name that highlighted the bug)

**Comment by McKnight-42** [comment]
@caoilte Thank you for pointing this out, after trying to replicate your issue i'm wondering if you could give me a little more context? or additional config information in your projects.yml that might be pointing to a failing cause as we haven't been able to make capitals in either file name of a csv seed file or yml schema cause failure.

**Comment by caoilte** [comment]
Hi @McKnight-42 ,
Our steps were,
1) create a GBQ dataset with a capitalised name (eg "caoilte_Bananas_raw"). This worked fine for a few weeks as a source.
2) create a seed which was assigned to dataset "caoilte_Bananas_raw". This failed with the above.

We never had a problem with capitals in the file names. It was always the dataset that it was assigned to which caused a problem.

However, we've also since banned capitalised letters in our dataset and table names to de-risk ourselves. So if you're unable to reproduce we won't be greatly inconvenienced at this point.

**Comment by McKnight-42** [comment]
@caoilte thank you for the furthered context so far we have tried the following please let me know if I've missed anything.

1. created a seed csv file named test.csv and tried it locally with a dbt seed which worked
2. changed name to Test.csv and tried again which also worked.
3. set up a seed configuration in project.yml for Test which also passed
4. made sure file name and configure name were different which also worked with dbt seed
5. also tried creating a federated table and added it to big query as a table in a dataset and using it as a source for a seed which did not get picked up as the seed file itself wasn't a csv file.

**Comment by caoilte** [comment]
Yeah. I'm struggling to reproduce in a fresh project. Maybe there's something weird about our macro to use part of our resource paths as dataset names. happy to close.

**Comment by McKnight-42** [comment]
@caoilte alright, thank you for following up with us, I will close this issue for now if it or something similar comes up again please reach out.
