### ISSUE TITLE
[ADAP-833] [CT-2992] [Regression] bigquery table goes missing while model is being loaded in certain scenarios

### ISSUE THREAD

**Issue by sarathadmail** [dbt-labs/dbt-bigquery#885]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

We have recently upgraded to dbt-core 1.6.0 version from 1.4.5 and noticed that a couple of tables are missing from the data base while the model is running. 

- The tables eventually will get created, but the queries that hit those tables during the load time are failing. 
- One of the model takes a long time to complete, so the table is missing in the db for that long which is problematic. 
- Bigquery time travel functionality where we can recover the data from any time in the last 7 days is also not working saying these is no history on these tables once they do get created or while they are missing in the db. 
- After debugging we found a specific scenario where this is happening while the same was not happening on 1.4.5
- The table should be partitioned and the model is doing a full load. 
- We have tables that are partitioned and being loaded in incremental mode, they are working fine. 
- tables that are not partitioned but being loaded either in incremental logic or full load are working fine. 

### Expected Behavior

Table should always be present even when the load is happening. 

### Steps To Reproduce

1. Install version 1.6.0
2. create a model that loads a BQ table in full load
3. partition the table on date. 
4. run the model and check for the presence of the table while the load is happening. 

### Environment

```markdown
- OS:
- Python:3.9.1
- dbt:1.6.0
```

### Which database adapter are you using with dbt?

bigquery

**Comment by github-christophe-oudar** [comment]
Likely the same as https://github.com/dbt-labs/dbt-bigquery/issues/886 as mentioned by @karanhegde for which I submitted a bug fix PR.

**Comment by sarathadmail** [comment]
> Likely the same as #886 as mentioned by @karanhegde for which I submitted a bug fix PR.

thanks @github-christophe-oudar

**Comment by dbeatty10** [comment]
Thanks for submitting this issue @sarathadmail !

I'm going to close this in favor of https://github.com/dbt-labs/dbt-bigquery/issues/886
