### ISSUE TITLE
[ADAP-872] [Feature] `copy_partitions` should be parallelizable

### ISSUE THREAD

**Issue by Kayrnt** [dbt-labs/dbt-bigquery#908]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

all partitions can be copied independently and concurrently. Then we could try to run concurrent jobs but maybe we should cap them to the max threads.

### Describe alternatives you've considered

According to https://cloud.google.com/bigquery/docs/managing-partitioned-tables#copy_a_partitioned_table:
> Copying multiple partitioned tables
If you copy multiple source tables into a partitioned table in the same job, the source tables can't contain a mixture of partitioned and non-partitioned tables.
If all of the source tables are partitioned tables, the partition specifications for all source tables must match the destination table's partition specification.

Indeed [copy_table](https://github.com/dbt-labs/dbt-bigquery/blob/2c7220a9afa59f7a7cf5e456a0b609954f1c38e2/dbt/adapters/bigquery/impl.py#L515) supports a list and not only a single element.

Then we can use the list with all the partitions that way to be much faster as we all partitions will be inserted concurrently instead of sequentially... **however it would delete any existing partitions making it unusable as is.**

### Who will this benefit?

Anyone using `copy_partitions`

### Are you interested in contributing this feature?

yes

**Comment by david-mag** [comment]
@Kayrnt I've just stumbled on the `copy_partition` feature in dbt. It really makes a HUGE difference in cost, when working with partitions in dbt for us, and I'm surprised, its not advertised more on the dbt docs (only place I could find a reference to it was hidden in insert-overwrite section [here](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#the-insert_overwrite-strategy) and a blog-post from you ^^). When working with partitions in BQ, I believe the MERGE strategy is a big waste and copying data into their proper partitions really being the _only_ sensible way.

However, when we were combining the `copy_partitions` parameter with `on_schema_change='sync_all_columns'`, we realized that the query creating the `*__dbt_tmp` was executed twice. I suspect that the way it is set up, it runs it once to check for schema changes, and once for copying the data (after deactivating the schema change parameter, the temp table creation was only run once).

**Comment by github-christophe-oudar** [comment]
@david-mag, yes it's not a default but I use it a lot (that's also why I introduced it 😉 ).
I guess the documentation could be improved to make it more explicit (cc @Fleid).

Regarding the double execution, it's a bug [I fixed in 1.7 branch](https://github.com/dbt-labs/dbt-bigquery/commit/6a2a90ccfa2a705672ddaccc74f050c09e45cff6). Try [1.7rc1](https://github.com/dbt-labs/dbt-bigquery/releases/tag/v1.7.0rc1), it should work as intended.

**Comment by david-mag** [comment]
Awesome! Thx for these updates. It really helps us keep the costs down, and making dbt a more viable tool :)
