### ISSUE TITLE
[ADAP-882] [Feature] Allow base64-service-account-json key auth

### ISSUE THREAD

**Issue by ismailsimsek** [dbt-labs/dbt-bigquery#923]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-bigquery functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allow setting gcp service account as base64 value. currently it only supports setting file path. it should be possible to set base64 SA value using environment variable.

similar to https://github.com/dbt-labs/dbt-snowflake/issues/436
implementation https://github.com/dbt-labs/dbt-snowflake/pull/292
https://github.com/dbt-labs/dbt-core/issues/6018

**Comment by dbeatty10** [comment]
Thanks for this suggestion @ismailsimsek !

Currently, there are two service account methods available in dbt-bigquery:
1. [Service Account File](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-file) (via `keyfile`)
2. [Service Account JSON](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-json) (via `keyfile_json`)

Did you already see the second method?

Assuming so, how would you imagine your suggestion being implemented?

Here's the relevant code within dbt-bigquery that interfaces with BigQuery:
https://github.com/dbt-labs/dbt-bigquery/blob/27ade3df84b040d4140c1870a033b20c2495b5cd/dbt/adapters/bigquery/connections.py#L330-L336

[Here](https://cloud.google.com/bigquery/docs/samples/bigquery-client-json-credentials) are the BigQuery docs for the two different methods:
- `from_service_account_file`
- `from_service_account_info`

**Comment by ismailsimsek** [comment]
@dbeatty10  from dbt side, this should work:
```python
# new method 
 elif method == BigQueryConnectionMethod.SERVICE_ACCOUNT_BASE64_JSON: 
     sa_json_base64 = profile_credentials.keyfile_base64_json 
     sa_json_content = base64.b64decode(details_base64.encode("utf-8")).decode("utf-8")
     return creds.from_service_account_info(info=sa_json_content) 
```

from bigquery lib this method could be used 
```python
    def from_service_account_info(cls, info, **kwargs):
```

**Comment by dbeatty10** [comment]
What do you think of this @dataders ?

The proposal is to add a third method named  `keyfile_base64_json` that is related to [BigQuery service account credentials](https://cloud.google.com/bigquery/docs/samples/bigquery-client-json-credentials) stored in JSON:
- [`keyfile`](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-file)
- [`keyfile_json`](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-json)
- `keyfile_base64_json` ← Newly proposed

Two alternatives to consider:
1. Allow Base64-formatted JSON data within `keyfile_json` and/or `keyfile` (and then do fancy footwork within the implementation to recognize this case, decode it, and call the applicable method)
2. Choose not to support Base64-formatted JSON data and direct folks to use pre-existing `keyfile_json` or `keyfile` methods instead

**Comment by dataders** [comment]
@dbeatty10 I support this. In fact, I'd love to mainstream key handling into the default implementation. imo, a single implementation reduces risk. Happy to accept a PR adding support for `keyfile_base64_json` for the short- and medium-term, but long-term is that this lives in a common implementation 

In a larger theme of authentication, I'd love to handle token handling as it related to cloud providers such as AWS and Azure. https://github.com/dbt-labs/dbt-core/issues/8186 is one example and MSFT adapter family token-handling ([source](https://github.com/dbt-msft/dbt-sqlserver/blob/9546c40044c82c46cdd3383fc14448a0d28d405a/dbt/adapters/sqlserver/sql_server_connection_manager.py#L201-L215)) is another.

**Comment by rbaker1** [comment]
I saw this issue and was wondering if you would accept a reimplementation of `BigQueryConnectionMethod.SERVICE_ACCOUNT_JSON`?

I can implement an `is_base64_encoded` method that will check if the string is base64 encoded. If it returns True, then the input will be decoded.


`    import base64
    import binascii
    
    def is_base64(s: str | bytes) -> bool:
        """
        Checks if the given string or bytes object is valid Base64 encoded.

        Args:
            s: The string or bytes object to check.

        Returns:
            True if the input is valid Base64, False otherwise.
        """

        if isinstance(s, str):
            # For strings, ensure they consist only of valid Base64 characters
            if not s.isascii():
                return False
            # Convert to bytes for decoding
            s = s.encode('ascii') 

        try:
            # Use the 'validate' parameter to enforce strict Base64 decoding rules
            base64.b64decode(s, validate=True)
            return True
        except binascii.Error:  # Catch specific errors from the base64 module
            return False`

Then a simple if-else will decode the base64 or leave the string as is.
