### ISSUE TITLE
[ADAP-906] [Bug] pip install dev-requirements only works on the second attempt

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-bigquery#931]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

See https://github.com/dbt-labs/dbt-snowflake/issues/784

### Expected Behavior

See above

### Steps To Reproduce

See above

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```

**Comment by mikealfare** [comment]
dev-requirements.txt is going away.
