### ISSUE TITLE
[ADAP-909] Fix mypy Failure

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-bigquery#934]
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Code quality check in GitHub fails with latest dbt-core due to new type annotations.

**Comment by dbeatty10** [comment]
Appears to be resolved by https://github.com/dbt-labs/dbt-bigquery/pull/933
