### ISSUE TITLE
[ADAP-960] The integration tests did not run since this is only a change to `setup.py`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-bigquery#982]
> The integration tests did not run since this is only a change to `setup.py` (we need to fix this). I kicked them off manually here: https://github.com/dbt-labs/dbt-bigquery/actions/runs/6645236952

_Originally posted by @mikealfare in https://github.com/dbt-labs/dbt-bigquery/issues/980#issuecomment-1779924874_

**Comment by mikealfare** [comment]
This will be handled by the new workflows in the monorepo.
